const fs = require("fs");
const JSZip = require("jszip");
(async () => {
  const zip = await JSZip.loadAsync(fs.readFileSync("Protocol_Flamingo_Rev2.docx"));
  let xml = await zip.file("word/document.xml").async("string");
  const old = "The memo sat between them while they did it.";
  const neu = "The memo sat between them anyway.";
  if (!xml.includes(old)) throw new Error("memo sentence missing");
  xml = xml.replace(old, neu);
  const cover = "without anyone official having to notice it.";
  const cover2 = "without anyone official noticing.";
  if (!xml.includes(cover)) throw new Error("cover sentence missing");
  xml = xml.replace(cover, cover2);
  // appendix claim links
  const gen = xml.indexOf("a real engineering literature");
  console.log("engineering context ids", xml.slice(gen, gen + 800).match(/r:id="rId\d+"/g));
  const mvp = xml.indexOf("minimum viable population");
  console.log("mvp ids", xml.slice(Math.max(0, mvp - 200), mvp + 400).match(/r:id="rId\d+"/g));
  const br = xml.indexOf("Ronald Bracewell");
  console.log("brace ids", xml.slice(br, br + 900).match(/r:id="rId\d+"/g));
  const sectP = xml.indexOf("lowerRoman");
  const pStart = xml.lastIndexOf("<w:p", sectP);
  const t = [...xml.slice(pStart, sectP).matchAll(/<w:t[^>]*>([^<]*)<\/w:t>/g)].map(m => m[1]).join("");
  console.log("section ends after:", t.slice(0, 180));
  zip.file("word/document.xml", xml);
  const buf = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
  fs.writeFileSync("Protocol_Flamingo_Rev2.docx", buf);
  const o = (xml.match(/\u201C/g) || []).length;
  const c = (xml.match(/\u201D/g) || []).length;
  console.log("quotes", o, c, "bytes", buf.length);
  if (o !== c) throw new Error("quotes");
})();
