# -*- coding: utf-8 -*-
"""One-off sentence fixes for the old building metaphor (Tower, floors, lifts,
staircases).  Keys: 0 = every volume, N = Volume N only.  Each pair is
(source text, replacement); matched against the SOURCE paragraph text, before
the vocabulary rules, and they win over the rules where they overlap."""
FIXES = {
 0: [
  ('Before going up, consider going back down one floor — the one that nagged at you.', 'Before going on, consider going back one chapter — the one that nagged at you.'),
  ("The useful report names the volume, the floor, and the room.", "The useful report names the volume, the chapter, and the section."),
  ("When a floor genuinely interests you, leave the building", "When a chapter genuinely interests you, read beyond the book"),
  ("a single continuous walk through the whole building", "a single continuous walk through the whole book"),
  ("a single continuous walk through the entire building", "a single continuous walk through the entire book"),
 ],
 1: [
  ('The View from the Top of This Particular Staircase', 'The View from the End of This Chapter'),
  ('Packing the Toolbox for the Climb', 'Packing the Toolbox for the Journey'),
  ('Lift notice — trigonometry ahead', 'Advance notice — trigonometry ahead'),
  ('Handing the Arrows Upstairs', 'Handing the Arrows Onward'),
  ('Turn Out to Be the Same Building', 'Turn Out to Be the Same Story'),
  ('load-bearing wall for something above it', 'load-bearing wall for something later'),
  ('’s algebra upward', '’s algebra onward'),
  ('The floor is flat, the two walls beside you are flat', 'The floor is flat, the two walls beside you are flat'),
  ('Mind the step on the way up to', 'Mind the step on the way into'),
  ('The walls, for once, are load-bearing.', 'The geometry, for once, is load-bearing.'),
  ('waits just above:', 'comes next:'),
  ('since we’re several floors up and can afford', 'since we’re several chapters in and can afford'),
  ('The Tower continues upward, one floor of understanding stacked on the last, and — appropriately for a Tower about dependence — each floor needs the one below it rather more than it likes to admit.', 'The series continues, one chapter of understanding built on the last, and — appropriately for a series about dependence — each chapter needs the one before it rather more than it likes to admit.'),
  ('Do not mistake this room for a list', 'Do not mistake this section for a list'),
  ("where the climb begins", "where the book begins"),
  ("is required to start climbing", "is required to begin"),
  ("standing at the foot of a very tall building, about to start climbing", "at the start of a long book, about to begin"),
  ("all the way up through geometry", "all the way through geometry"),
  ("somewhere around the eyrie labeled", "somewhere around the chapter labeled"),
  ("So we begin at the bottom,", "So we begin at the beginning,"),
  ("a tower built on a foundation of guesswork tends not to stay a tower for very long", "anything built on a foundation of guesswork tends not to stay standing for very long"),
  ("the long ascent through the rest of the tower", "the long road through the rest of the series"),
  ("the more elaborate machines waiting upstairs", "the more elaborate machines waiting later in the book"),
  ("take the lift up to ", "jump ahead to "),
  ("and come straight back down", "and come straight back"),
  ("It’s worth pausing at the top of this particular flight of stairs to take stock, because everything below us in this room is infrastructure", "It’s worth pausing here to take stock, because everything so far in this section is infrastructure"),
  ("It is worth pausing at the top of this particular staircase and looking back down it, because the view clarifies something that was easy to miss while climbing one step at a time.", "It is worth pausing at the end of this chapter and looking back, because the view clarifies something that was easy to miss while working one step at a time."),
  ("The view from the top of this particular staircase", "The view from the end of this chapter"),
  ("multiplication downstairs becomes addition upstairs", "multiplication on one side becomes addition on the other"),
  ("A third corridor, reached", "A third path, reached"),
  ("for a room or two", "for a section or two"),
  ("no infinite descending staircase of positive whole numbers", "no infinite descending staircase of positive whole numbers"),
 ],
 2: [
  ('The Tower Continues Upward', 'The Series Continues'),
  ('Packing the Toolbox for the Climb Ahead', 'Packing the Toolbox for the Road Ahead'),
  ('The View From the Landing', 'The View From Here'),
  ('the Basement note in the front matter', 'the note on foundations in the front matter'),
  ('Where the Tower Goes Next', 'Where the Series Goes Next'),
  ('and for once, the descent is part of the plan', 'and for once, the step back is part of the plan'),
  ('in every room for the rest of this', 'in every section for the rest of this'),
  ('the last example in the room is', 'the last example in the section is'),
  ('next floor under the name', 'next chapter under the name'),
  ('no tower of reasoning — not even this one', 'no chain of reasoning — not even this one'),
  ("for a room or two", "for a section or two"),
  ("Somewhere on the climb up from ", "Somewhere after "),
  ("the building committee has decided", "the syllabus has decided"),
  ("The height of the actual staircase you are climbing depends on both how far east and how far north you have wandered from the lobby.", "The height of the hillside you are walking on depends on both how far east and how far north you have wandered from the trailhead."),
  ("is a concern for a later landing", "is a concern for a later chapter"),
  ("worth carrying up every remaining staircase", "worth carrying into every remaining chapter"),
  ("We came up this staircase with", "We began this chapter with"),
  ("if it must be compressed into one sentence for the lift journey to the next floor", "if it must be compressed into one sentence on the way to the next chapter"),
  ("the scaffolding becomes the building", "the scaffolding becomes the structure"),
  ("several floors we have already climbed", "several chapters we have already worked through"),
  ("climb up into abstraction for an entire floor, then climb straight back down into the concrete", "go up into abstraction for an entire chapter, then come straight back down into the concrete"),
  ("The plan of this floor is to climb the second-degree ladder", "The plan of this chapter is to work up the second-degree ladder"),
  ("We will climb from the algebra", "We will travel from the algebra"),
  ("A landing at the top of the stairs, with several unmarked doors leading further up", "At the end of the chapter, several unmarked doors leading onward"),
  ("if it must be compressed into a single sentence for the lift doors closing behind us", "if it must be compressed into a single sentence before we move on"),
  ("It is worth pausing on the landing before the next flight of stairs", "It is worth pausing here, before the next chapter"),
  ("The moral is worth carrying upstairs", "The moral is worth carrying forward"),
 ],
 3: [
  ('Up here on the thirty-third floor we reverse', 'Here in the thirty-third chapter we reverse'),
  ('The Tower Keeps Building', 'The Series Keeps Building'),
  ('which, at this altitude, counts as good news', 'which, at this stage, counts as good news'),
  ('Floor 34s machinery', 'Chapter 34’s machinery'),
  ('just one floor taller', 'just one level taller'),
  ('this floor never defined', 'this chapter never defined'),
  ('needed this floor underneath it', 'needed this chapter underneath it'),
  ("so that the map of the Tower stays legible from up here", "so that the map of the series stays legible from here"),
  (", upstairs in this very volume)", ", later in this very volume)"),
  ("The view from the thirty-third floor, before the lift doors close", "The view from the thirty-third chapter, before we move on"),
  ("on the landing here at the top of ", "here at the end of "),
  ("last seen counting holes upstairs", "last seen counting holes in topology"),
  ("was already sitting downstairs the whole time", "was already in place the whole time"),
  ("we shall spend the rest of the Tower’s climb standing on a floor we never poured", "we shall spend the rest of the series standing on a foundation we never poured"),
  ("which building you are standing in", "which subject you are standing in"),
  ("which is the recurring experience of climbing this building", "which is the recurring experience of working through this book"),
  ("the same choice the basement note defended", "the same choice the note on foundations defended"),
  ("further up than we will climb today", "further than we will go today"),
 ],
 4: [
  ('Where the Tower Meets the World', 'Where Mathematics Meets the World'),
  ('Onward and, as always in this Tower, upward.', 'Onward, as always in this series.'),
  ('considerably taller than it looks from here', 'considerably longer than it looks from here'),
  ('when the floor is no longer flat', 'when the ground is no longer flat'),
  ('Take one floor and go outside the Tower.', 'Take one chapter and go outside the book.'),
  ('; below that, forty-eight', '; before that, forty-eight'),
  ('Below us: ', 'Behind us: '),
  ('it simply gets a rigorous floor poured underneath it', 'it simply gets a rigorous foundation poured underneath it'),
  ("The Tower and What Lies Beyond", "The Series and What Lies Beyond"),
  ("This capstone floor assumes the whole climb behind it", "This capstone chapter assumes the whole journey behind it"),
  ("with the usual caution issued at every landing of this Tower: the view improves the higher you climb, but so, regrettably, does the drop", "with the usual caution issued at every chapter of this series: the view improves the further you go, but so, regrettably, does the difficulty"),
  ("the climber’s legs may be glad of", "the reader may be glad of"),
  ("We will climb through entropy", "We will work through entropy"),
  ("as rigorous as anything upstairs in this Tower", "as rigorous as anything else in this series"),
  ("We have now climbed through", "We have now worked through"),
  ("sends the bill upstairs for the foundations", "sends the bill forward for the foundations"),
  ("descends, or perhaps ascends sideways, into", "moves, sideways perhaps, into"),
  ("The plan of ascent:", "The plan of the chapter:"),
  (" looks up the staircase toward ", " looks ahead toward "),
  ("before the staircase turns", "before the chapter turns"),
  ("much further up the tower of difficulty", "much higher up the scale of difficulty"),
  ("The lift doors open on the forty-eighth floor with the particular judder that tells you the shaft alignment is, once again, not your department.", "The forty-eighth chapter opens with the particular judder that tells you the ground has shifted again, and not gently."),
  ("if it has to be compressed into one sentence for the lift ride down", "if it has to be compressed into one sentence on the way out"),
  ("four floors short of the roof", "two chapters short of the end"),
  ("Take the lift.", "Skip ahead."),
  ("If you have climbed them all in order — and if you have not, no matter, the lift still runs, though the buttons above thirty or so require a certain faith —", "If you have read them all in order — and if you have not, no matter, the book still works, though the chapters past thirty or so require a certain faith —"),
  ("you now stand somewhere considerably higher, having lately passed through the numerical-methods floor below", "you now stand somewhere considerably further on, having lately passed through the numerical-methods chapter just before this one"),
  ("The lift, mercifully, also goes back down.", "The book, mercifully, also reads backwards: every chapter is still there when you want it."),
  ("the single relation everything else in the room is built from", "the single relation everything else in the subject is built from"),
  ("has a configuration space that is the room itself, minus the obstacles", "has a configuration space that is the room itself, minus the obstacles"),
 ],
}
