# -*- coding: utf-8 -*-
# First-pass boxes: the result and its meaning before the derivation.
FP = {
1: ("Complex numbers are the arrows of Prologues 1–4; vectors, inner products and matrices are the bookkeeping for many arrows at once. Every later lesson writes amplitudes as complex numbers, probabilities as |amplitude|², and physical quantities as Hermitian matrices.",
    "If Prologue 4 felt comfortable, Section 1 is a fast review; the new material starts with vector spaces in Section 2."),
3: ("Space and time intervals depend on the observer, but the interval s² = (ct)² − x² − y² − z² does not. Moving clocks run slow by γ = 1/√(1 − v²/c²) and moving rods shrink by the same factor.",
    "The invariant interval is the seed of every Lorentz-invariant quantity in QED, from p² = m² to the Mandelstam variables."),
4: ("Four-vectors x^μ, p^μ transform with one matrix Λ, and the metric g = diag(1, −1, −1, −1) turns any pair into an invariant a·b = a⁰b⁰ − a·b. For a particle, p·p = E² − |p|² = m².",
    "Every amplitude in Lessons 50–79 is built from such dot products, so learning to contract indices here pays off on every later page."),
5: ("Nature's path makes the action S = ∫L dt stationary, and that one requirement gives the Euler–Lagrange equation d/dt(∂L/∂q̇) = ∂L/∂q, which reproduces Newton's laws.",
    "This is Prologue 3's 'least time' for particles. The same rule, applied to fields in Lessons 26–27, gives every field equation in the course."),
7: ("Four equations relate E and B to charges and currents; in empty space they combine into waves travelling at c. Energy flows with the Poynting vector S = E × B.",
    "This is Prologue 7's many-photon language in full. Lesson 8 rewrites it with potentials, which QED needs."),
8: ("E and B can be written as E = −∇φ − ∂A/∂t and B = ∇ × A, and the potentials can be shifted by a gauge transformation A → A + ∇λ, φ → φ − ∂λ/∂t without changing E or B.",
    "The freedom looks like a nuisance classically. In Lesson 39 it becomes the principle that generates the whole electron–photon interaction."),
10: ("A quantum state is a vector |ψ⟩ in a complex vector space; amplitudes are inner products ⟨φ|ψ⟩; probabilities are |⟨φ|ψ⟩|²; and states must be normalized, ⟨ψ|ψ⟩ = 1.",
    "These are Prologue 8's bras and kets with the full rules attached."),
12: ("The state changes in time by iℏ ∂ψ/∂t = Ĥψ. A state of definite energy just turns its arrow, ψ(t) = φ e^(−iEt/ℏ), so its probabilities do not change; superpositions of different energies change in time.",
    "This is the stopwatch of Prologue 1, now with the turning rate set by energy."),
16: ("When the Hamiltonian is a solvable part plus a small extra piece, energies and states can be expanded in powers of the small piece: E⁽¹⁾ = ⟨n|H′|n⟩, and E⁽²⁾ = Σ|H′ₘₙ|²/(Eₙ − Eₘ).",
    "QED's whole calculational method, from Lesson 45 on, is this idea with the small piece being the electron–photon coupling e."),
18: ("Turning E² = p² + m² into a wave equation gives the Klein–Gordon equation (□ + m²)φ = 0. It is relativistic, but it allows negative energies and a probability density that can be negative.",
    "The problem is real, not a mistake in the derivation; Lessons 20, 23 and 32 resolve it."),
20: ("Dirac found a first-order relativistic equation, (iγ^μ∂_μ − m)ψ = 0, whose matrices obey {γ^μ, γ^ν} = 2g^μν. Its solutions have four components, and squaring the equation gives back Klein–Gordon.",
    "Four components means spin up and down for both the electron and its antiparticle; the γ matrices will appear in every electron vertex."),
21: ("Gamma-matrix algebra reduces to a few identities: γ_μγ^μ = 4, traces of odd numbers of γs vanish, Tr[γ^μγ^ν] = 4g^μν, and the four-γ trace formula.",
    "Every cross section in Lessons 54–58 is a trace evaluated with exactly these rules. This is one of the high-risk topics: keep the identity table at hand."),
22: ("The adjoint ψ̄ = ψ†γ⁰, not ψ†, makes covariant combinations, and sixteen bilinears ψ̄Γψ classify how they transform. A Dirac particle at rest has spin 1/2.",
    "The current ψ̄γ^μψ built here is the thing the photon couples to in QED."),
23: ("Negative-energy solutions are reinterpreted as positive-energy antiparticles travelling forward in time: the positron.",
    "This is Prologue 5's 'electron running backwards in time' made exact; it is why one diagram describes pair creation, annihilation and scattering."),
26: ("A field theory is specified by a Lagrangian density ℒ(φ, ∂_μφ), and the action is S = ∫d⁴x ℒ. Lorentz invariance of ℒ guarantees relativistic field equations.",
    "QED itself will be a single Lagrangian density (Lesson 42)."),
28: ("Every continuous symmetry of the action gives a conserved current: ∂_μj^μ = 0. For the phase symmetry ψ → e^(iα)ψ of the electron field, the current is ψ̄γ^μψ.",
    "Charge conservation is a consequence of a phase symmetry. Making that phase local is the step that creates QED (Lesson 39)."),
33: ("Imposing [φ(x), π(y)] = iδ³(x − y) turns a classical field into infinitely many quantum oscillators, one per momentum, with creation and annihilation operators a_p†, a_p.",
    "Each quantum of an oscillator is a particle: this is where 'particles are excitations of a field' becomes a calculation."),
36: ("The Dirac field is expanded in operators b (destroy electrons) and d† (create positrons) that anticommute, {b, b†} = (2π)³δ³; no state holds two identical fermions.",
    "These operators are the electron lines of every diagram; the anticommutation is the origin of the relative minus signs in Lessons 55 and 63."),
38: ("Gauge freedom removes two of the four components of A_μ; in Coulomb gauge the photon has two transverse polarizations, each an oscillator with a†_kλ, a_kλ.",
    "Two polarizations per momentum is the photon of Prologues 1–6, now as a quantized field. Lesson 71 returns to the gauge choice covariantly."),
39: ("Demanding that physics be unchanged under a phase rotation that differs from point to point, ψ → e^(iα(x))ψ, forces a new field A_μ and the covariant derivative D_μ = ∂_μ + ieA_μ.",
    "The electromagnetic interaction is not added by hand: it is the price of a local phase freedom. This is a high-risk topic; the derivation is worth doing twice."),
40: ("Expanding the gauge-invariant Dirac Lagrangian gives the interaction −eψ̄γ^μψA_μ: the current of Lesson 28 coupled to the potential. Its non-relativistic limit is the familiar coupling to φ and A.",
    "One term reproduces every classical electromagnetic coupling met so far."),
41: ("Covariant derivatives do not commute: [D_μ, D_ν] = ieF_μν. The field strength is the 'curvature' of the phase connection A_μ.",
    "E and B are what is left when you go round a small loop and compare phases: the bridge to Mead's view in the following Interlude."),
42: ("ℒ_QED = ψ̄(iγ^μD_μ − m)ψ − ¼F_μνF^μν. Varying ψ̄ gives the Dirac equation with the photon coupling; varying A gives Maxwell's equations with the electron current as source.",
    "This one line is the whole theory. Everything from Lesson 43 on is extracting its consequences."),
44: ("The coupling e is dimensionless in natural units, with α = e²/4π ≈ 1/137. Each vertex brings one power of e, so amplitudes are series in α.",
    "Prologue 5's j ≈ −0.1 is √α up to convention; smallness of α is why perturbation theory works."),
45: ("First-order perturbation theory with the mode expansions gives the vertex factor ieγ^μ (this course's sign convention) and momentum conservation at the vertex. A single vertex with all particles real cannot conserve energy and momentum.",
    "The vertex is a building block, not a process: real processes need at least two vertices."),
46: ("The Feynman propagator Δ_F = i/(p² − m² + iε) is the Green's function of the Klein–Gordon operator; the iε chooses positive energies forward in time and negative energies backward.",
    "This is Prologue 5's 'goes from point to point' with a formula; Figure 46.1 shows where the iε moves the poles."),
47: ("The electron propagator is S_F(p) = i(p̸ + m)/(p² − m² + iε), obtained as (i∂̸ + m) acting on the scalar propagator, with a minus sign in fermionic time ordering.",
    "Its numerator p̸ + m is the spin sum Σuū, which is why internal electron lines carry every spin state."),
48: ("The photon propagator is D_F^μν(k) = −ig^μν/(k² + iε) in Feynman gauge; the Coulomb-gauge form gives the same physical answers.",
    "Gauge choice changes the propagator, not the predictions; Lessons 71–73 prove this in general."),
50: ("Every QED amplitude follows from a recipe: external-line factors (u, ū, v, v̄, ε, ε*), a vertex ieγ^μ at each junction, propagators for internal lines, momentum conservation at each vertex, and a loop integral with a minus sign for each closed fermion loop.",
    "This is the precise form of Prologue 5's three actions. Figure 50.1 collects the rules on one page."),
51: ("The rate of any process is |ℳ|² times a flux factor and phase space, after the (2π)⁴δ⁴ of momentum conservation has been squared and resolved.",
    "Squaring a delta function sounds illegal; done carefully it just gives the spacetime volume, which cancels against the flux."),
52: ("Spin sums turn |ūΓu|² into traces: Σuū = p̸ + m, Σvv̄ = p̸ − m, and the photon polarization sum can be replaced by −g_μν.",
    "This converts every unpolarized cross section into gamma-matrix traces (Lesson 21). High-risk topic: watch the signs."),
53: ("For 2 → 2 processes, s = (p₁ + p₂)², t = (p₁ − p₃)², u = (p₁ − p₄)², and s + t + u is the sum of the four squared masses; in the CM frame t and u are fixed by the energy and angle.",
    "Every result in Part VIII is written in s, t, u, which makes crossing between processes easy."),
54: ("Single-photon exchange gives, at high energy, (1/4)Σ|ℳ|² = 2e⁴(s² + u²)/t² for electron–muon scattering.",
    "The 1/t² is the photon propagator squared: a strong forward peak, Rutherford's formula in relativistic dress."),
55: ("Identical electrons need two diagrams, t- and u-channel, with a relative minus sign; the squared amplitude includes an interference trace.",
    "This is Prologue 5's reversed arrow for swapped electrons, now with spinors."),
56: ("e⁺e⁻ → γγ has two diagrams with a relative plus sign; at high energy (1/4)Σ|ℳ|² = 2e⁴[t/u + u/t].",
    "Bosons in the final state add without the Møller minus sign."),
57: ("For Compton scattering the interference term cancels, leaving (1/4)Σ|ℳ|² = −2e⁴(s/u + u/s) at high energy (positive, since u < 0). With the electron mass kept, this becomes the Klein–Nishina formula, which reduces to Thomson scattering at low energy.",
    "Light scattering off a free electron, the basic process behind Prologue 5's glass, now computed exactly."),
58: ("γγ → e⁺e⁻ reuses the annihilation result by crossing and needs s ≥ 4m², at least 1.022 MeV in the CM frame.",
    "Matter from light has a threshold: two electron masses of energy."),
59: ("For 2 → 2 in the CM frame, dσ/dΩ = |ℳ|²/(64π²s) (equal masses, or high energy).",
    "This one formula turns every |ℳ|² of Lessons 54–58 into a number a detector can check."),
60: ("A particle of mass M decaying to two bodies has dΓ/dΩ = p_f|ℳ|²/(32π²M²), with p_f fixed by the masses.",
    "Decay rates are the one-particle version of cross sections; the same phase-space reduction applies."),
62: ("A closed loop leaves one momentum k unfixed by conservation, so it must be integrated over; at large k the integral does not converge.",
    "Prologue 6's infinities appear here, honestly. Lessons 66–68 show where they go."),
63: ("The vacuum-polarization loop is iΠ^μν(q) = −e²∫d⁴k/(2π)⁴ Tr[γ^μ(k̸ + m)γ^ν(k̸ − q̸ + m)]/[(k² − m²)((k − q)² − m²)], which naively grows like Λ².",
    "A photon briefly becoming a pair is what makes the charge run (Lesson 69)."),
64: ("The self-energy Σ(p) = −ie²∫d⁴k/(2π)⁴ γ^μ(p̸ − k̸ + m)γ_μ/[((p − k)² − m²)k²] grows linearly with the cutoff by naive counting.",
    "It shifts the electron's mass: the mass in the Lagrangian is not the measured mass (Lesson 68)."),
65: ("The vertex correction inserts a photon across the vertex; it diverges only logarithmically, and its finite part contains the anomalous magnetic moment.",
    "This diagram, finished in Lesson 76, gives Schwinger's α/2π."),
66: ("Power counting gives the superficial degree D = 4 − (3/2)E_e − E_γ, so only diagrams with a few external legs can diverge.",
    "A finite list of divergences means a finite list of measured inputs can absorb them all: QED is renormalizable."),
67: ("After Wick rotation k⁰ = ik⁴_E and a cutoff Λ, the standard loop integral is i/(16π²)[ln(Λ²/Δ) − 1 + O(Δ/Λ²)]: a logarithm of the cutoff plus a finite part.",
    "Regularization makes the infinity a number you can see; renormalization (Lesson 68) then makes it disappear from predictions."),
68: ("The physical mass m is the pole of the full propagator, m = m₀ + A(m₀²) at leading order; since A diverges, the unmeasured m₀ must diverge to compensate, and predictions written in terms of m are finite.",
    "Prologue 6's 'use the measured mass and charge' as an equation. High-risk topic: follow the bookkeeping slowly."),
69: ("Resumming vacuum-polarization insertions gives an effective coupling that grows logarithmically with momentum transfer: α_eff(Q²) ≈ α/[1 − (α/3π)ln(Q²/(e^(5/3)m²))] for one lepton at large Q².",
    "The charge depends on how closely you look (Prologue 6, Figure P6.3; Figure 69.1 here)."),
70: ("The running is the solution of μ de/dμ = β(e) with β = e³/(12π²) > 0 for one lepton; solving it sums the leading logarithms.",
    "A positive β means QED gets stronger at short distances, the opposite of the strong force."),
71: ("Adding −(∂·A)²/(2ξ) makes the photon propagator exist: D_μν = −i[g_μν − (1 − ξ)k_μk_ν/k²]/(k² + iε). ξ = 1 is Feynman gauge, ξ = 0 Landau gauge.",
    "The extra ξ-dependent piece never reaches a physical answer (Lessons 72–73)."),
72: ("Current conservation becomes k_μℳ^μ = 0 for any amplitude with an external photon, and the Ward–Takahashi identity forces Z₁ = Z₂.",
    "Charge renormalization comes only from the photon's own loop, so every particle's charge runs the same way. High-risk topic."),
73: ("The S-matrix is the same in every gauge, covariant or Coulomb, even though Green's functions are not.",
    "Gauge is a choice of description; cross sections do not depend on it. High-risk topic."),
74: ("A massless photon makes the vertex integral diverge at small k; the probability of scattering with no radiation at all is zero.",
    "The cure is physical, not mathematical: a detector cannot see arbitrarily soft photons, and the rates it can measure are finite (Lesson 75)."),
75: ("Soft photons are emitted with the universal factor e[p′·ε/p′·k − p·ε/p·k]; their emission probability cancels the virtual infrared divergence.",
    "Every deflected charge radiates a cloud of soft photons; only the resolution ΔE survives in predictions."),
76: ("Dirac's g = 2 is corrected by the vertex loop to g = 2(1 + a), with a = F₂(0) = α/(2π) ≈ 0.00116.",
    "The first finite prediction of QED's loops, now confirmed to parts in 10¹²."),
77: ("Self-energy, the vertex and anomalous moment, and vacuum polarization split hydrogen's 2s₁/₂ and 2p₁/₂ levels by about 1058 MHz, dominated by Bethe's logarithm.",
    "The Lamb shift is the atomic-physics face of the same loops as Lessons 63–65."),
78: ("Vacuum polarization modifies Coulomb's law within about one electron Compton wavelength (the Uehling potential), lowering hydrogen's 2s level by about 27 MHz and dominating the Lamb shift in muonic hydrogen.",
    "Running α seen in an atom."),
}
# Plain-language starts for Lessons 2-9.
PLAIN = {
2: "This lesson is the calculus toolkit: derivatives say how fast something changes, integrals add up many small pieces, and differential equations say how a system changes from moment to moment. The one function to watch is the exponential: e^(−iωt) is Prologue 4's turning arrow, and it is the solution of the simplest differential equation, 'the rate of change is proportional to the thing itself'.",
3: "Two observers moving past each other disagree about lengths and times, but agree about the speed of light. Everything in this lesson follows from taking that fact seriously. If you have only school algebra, read Sections 1–2 slowly with the worked examples; the rest builds on them.",
4: "A four-vector is just four numbers (a time part and three space parts) that change in a fixed way when you change observer. The lesson's one trick is a 'dot product' with a minus sign, which gives numbers that every observer agrees on, such as a particle's mass.",
5: "Instead of forces, describe motion by a single number for each possible path, the action, and ask which path makes it stationary. This is Prologue 3's 'least time' rule, applied to particles instead of light, and it is how every theory in this course is written down.",
6: "The Hamiltonian is the energy written in terms of positions and momenta. It is the bridge to quantum mechanics: in Lesson 12 the same Hamiltonian becomes the machine that turns the arrows of a quantum state.",
7: "Maxwell's equations are four rules about how electric and magnetic fields are produced and how they change. Prologue 7 described them in words and pictures; this lesson writes them as equations and shows that together they predict light.",
8: "Instead of the fields E and B, describe electromagnetism by potentials: a 'height' φ and a 'flow' A from which the fields follow. The potentials have a built-in freedom, gauge freedom, which looks like a technicality here and becomes the founding principle of QED in Lesson 39.",
9: "This lesson connects the prologues' arrows to classical optics: why glass slows light, where Prologue 2's arrow of length 0.2 comes from, why every path contributes, and how a classical wave is many photons. Nothing in it needs more than Lessons 1–8.",
}
