# Section headings for the former Genetics chapters (they had none; the series style
# gives every chapter Heading 2 sections). key: chapter -> [(paragraph index, heading)].
# A heading placed on a '---' paragraph replaces that break.
H = {
30: [(0,'A Tube in the Mail'),(3,'Two Metres of Thread'),(6,'The Molecule Nobody Wanted'),(9,'What the Laboratory Will Read'),(12,'The Walk Home')],
31: [(0,'A Pub on Bene\'t Street'),(3,'An Odd Pair'),(7,'Cardboard Bases'),(13,'Metal Plates and One Sentence'),(16,'Why a Shape Settled It')],
32: [(0,'A Black Square With a Cross'),(4,'Rosalind Franklin'),(10,'The Decision She Made'),(12,'Two Transfers'),(16,'What Was Hers')],
33: [(0,'Unwinding the Model'),(2,'Chargaff\'s Rule'),(6,'Two Backbones, One Twist'),(9,'The First Prediction'),(13,'Information and the Dogma'),(16,'Accepted')],
34: [(0,'Pus on Bandages'),(4,'The Stupid Molecule'),(6,'Three Instalments'),(15,'The Blender Experiment'),(19,'Why It Took So Long')],
35: [(0,'What the Letters Are'),(8,'How Many Letters'),(14,'Packing Two Metres'),(19,'The Same Text in Every Cell')],
36: [(0,'Ten Thousand Reactions at Once'),(2,'Two Kinds of Bond'),(6,'Proteins, the Working Molecules'),(12,'Paying for It'),(18,'One Letter, One Disease')],
37: [(0,'A Cell That Lives Four Days'),(5,'The Fork'),(14,'The Errors'),(18,'The End Problem')],
38: [(0,'A Tape of U'),(4,'The Messenger'),(8,'Reading in Threes'),(16,'The Arrow and Its Exceptions')],
39: [(0,'The Recipe Is Short'),(2,'The Switches'),(4,'Jumping Genes and Debris'),(7,'How Much Is Functional'),(11,'Small RNAs and Distant Switches'),(14,'Marks on Top of the Letters')],
40: [(0,'Sixty New Letters'),(2,'Attacked Every Day'),(4,'The Repair Crews'),(5,'Four Kinds of Mistake'),(6,'The Ingredient Darwin Lacked'),(8,'Is Mutation Quantum?'),(17,'Copying\'s Shadow')],
41: [(0,'A Photograph on the Refrigerator'),(4,'Two Ways to Divide'),(11,'The Arithmetic of a Family'),(16,'An Egg Made in 1947')],
42: [(0,'A Queen\'s Eighth Child'),(3,'The Twenty-Third Pair'),(10,'Every Woman Is a Mosaic'),(13,'Lines That Do Not Shuffle')],
43: [(0,'The Worksheet'),(3,'One Gene, Two Copies'),(11,'The Middle'),(17,'Heritability')],
44: [(0,'The Hunger Winter'),(5,'Environment and Noise'),(10,'Genetic Is Not Fixed'),(15,'Can a Grandmother\'s Life Be Inherited?')],
45: [(0,'A Strip of Ground in Brno'),(2,'The Friar'),(7,'Why Peas'),(15,'Eight Seasons of Labour')],
46: [(0,'Five Thousand Four Hundred and Seventy-Four'),(5,'Segregation'),(12,'The Second Law'),(15,'An Evening in February 1865')],
47: [(0,'Three Men in 1900'),(3,'The Abbot'),(6,'Bateson Names the Field'),(10,'Where the Factors Lived'),(15,'Too Good to Be True?')],
48: [(0,'A Fly That Should Not Be There'),(5,'The Fly Room'),(12,'Giant Chromosomes'),(17,'Mendel With an Address')],
49: [(0,'A Laboratory at an Exhibition'),(3,'Three Generations'),(11,'The Mirror Image'),(15,'Three Errors')],
50: [(0,'A Bacterial Defence'),(5,'The First Recombinant Molecule'),(10,'Asilomar'),(14,'Insulin')],
51: [(0,'A Virus Read Letter by Letter'),(3,'The Ladder'),(11,'From Hands to Machines')],
52: [(0,'Highway 128'),(2,'The Chain Reaction'),(7,'An Enzyme From a Hot Spring'),(14,'The Hazard')],
53: [(0,'Monday Morning in Leicester'),(4,'The First Cases'),(9,'Profiles, Databases and Mistakes')],
54: [(0,'A Chart That Falls Off a Cliff'),(3,'Born in a Pub'),(7,'The Blind Spot and the Long Reads'),(12,'Everywhere')],
55: [(0,'A Problem in a Yogurt Factory'),(4,'From Immune System to Tool'),(9,'Cutting Is Not Editing'),(15,'What Nobody Predicted'),(19,'What CRISPR Really Changed')],
56: [(0,'Victoria Gray'),(3,'Thirty Years to Nashville'),(9,'Everything Around the Edit'),(14,'A Baby Named KJ')],
57: [(0,'A Genome Written by Machine'),(5,'How DNA Is Written'),(7,'Writing a Vaccine'),(10,'Writing Proteins'),(13,'Where Writing Is Still Hard')],
58: [(0,'A Finger Bone in Siberia'),(1,'DNA That Should Not Survive'),(5,'The Neanderthal Genome'),(9,'Rewriting Prehistory'),(12,'Dire Wolves and Woolly Mice')],
59: [(0,'A Shed South of Edinburgh'),(5,'The Older Puzzle'),(10,'Megan, Morag and Dolly'),(14,'Born Old?')],
60: [(0,'A Dog Named Samantha'),(6,'A Cat Named CC'),(10,'Cloning That Pays'),(17,'What Goes Wrong')],
61: [(0,'A Lecture Hall in Hong Kong'),(2,'After Dolly'),(9,'The Stem Cell Shortcut'),(12,'The Man at the Lectern')],
62: [(0,'An Ear of Corn and a Weed'),(5,'Wheat, Dogs and Darwin'),(10,'The Green Revolution'),(17,'Breeding by Waiting')],
63: [(0,'A Tomato in Davis'),(3,'The Crops That Mattered'),(7,'What Only the Technique Could Do'),(12,'Two Continents, Two Rules'),(14,'The First Edited Foods')],
64: [(0,'A Photograph in Poultry Science'),(4,'The Salmon and the Hornless Cattle'),(10,'Pigs and Chickens'),(12,'Cloned Meat and the Welfare Question')],
65: [(0,'A Weed in Georgia'),(4,'Gene Flow and Monoculture'),(7,'The Seed Companies'),(13,'The Risk That Is Not One')],
66: [(0,'The East Room, June 2000'),(3,'Alta, Utah'),(8,'Bermuda and Venter'),(14,'Two Drafts, One Text')],
67: [(0,'A Bet at a Bar'),(3,'How the Parts Are Used'),(10,'The Last Eight Percent'),(14,'A Pangenome')],
68: [(0,'Half a Million Volunteers'),(3,'The Graveyard of Common Disease'),(9,'Adding Small Effects Up')],
69: [(0,'Six Weeks After the Mailbox'),(2,'The Company'),(9,'What the Chip Reads'),(14,'Relatives and the Health Tab')],
70: [(0,'An Op-Ed in May 2013'),(3,'Repair Genes and Penetrance'),(7,'Through a Family'),(12,'Drugs and Newborns')],
71: [(0,'A Height Chart'),(2,'Variants That May Not Act'),(4,'Small Pieces'),(9,'Intelligence'),(12,'Chance')],
72: [(0,'An Arrest in Sacramento'),(4,'The Arithmetic of Cousins'),(7,'Insurance and Ownership'),(12,'Companies and States')],
73: [(0,'A Thawed Vial'),(5,'Somatic and Germline'),(12,'Delivery'),(18,'Seven Thousand Rare Diseases')],
74: [(0,'A Summit in London'),(3,'The Case For and Against'),(9,'Already Across the Line'),(16,'The Rules')],
75: [(0,'A Boy in Berlin'),(2,'The Short List'),(12,'The Accounting'),(15,'Doping and Intelligence')],
76: [(0,'A Wall in 2126'),(3,'What Is Already Happening'),(10,'The Working Guesses'),(19,'Allowed, Not Shown')],
}
