# Uniform chapter titles in the Physics, Actually form "Main Title — Subtitle".
TITLES = {
 1: "What Is Life — Schrödinger's Question and the Order in the Disorder",
 3: "How Life Started — Clay, Vents, RNA and the First Protocells",
 21: "Brains and Instincts — The Evolution of Behavior",
 22: "The Strange Loop — Evolution and Self-Reference",
 23: "Analogy, Language and Culture — Evolution Beyond Genes",
 26: "Building a Mind — Evolution and AI",
 27: "The Feeling of Being — Consciousness, Evolution and AI",
 30: "The Tube in the Mailbox — Where the Molecule Comes In",
 31: "The Eagle, 28 February 1953 — A Shape Announced in a Pub",
 32: "Photo 51 — Rosalind Franklin's Picture",
 33: "What the Shape Explains — Pairs, Twists and the Central Dogma",
 34: "The Race Before the Race — How DNA Was Shown to Be the Gene",
 35: "Four Letters — The Alphabet and How It Is Packed",
 36: "The Chemistry Under the Letters — Bonds, Proteins and Energy",
 37: "The Copying Machine — Forks, Errors and Ends",
 38: "From Letter to Protein — The Messenger and the Code",
 39: "Most of the Text Is Not Genes — Switches, Jumping Genes and Marks",
 40: "Where Mistakes Come From — Damage, Repair and Mutation",
 41: "Why Theo Has Ruth's Freckles — How Inheritance Shuffles",
 43: "Dominant and Recessive — The Messy Middle and Heritability",
 44: "What Is Not in the Genes — Environment, Noise and Epigenetics",
 46: "The Ratios — Mendel's Counts and Laws",
 47: "Lost for Thirty-Five Years — Rediscovery and the Birth of Genetics",
 48: "Flies in a Bottle — Morgan and the Chromosome Theory",
 49: "Galton's Shadow — The Eugenics Disaster",
 50: "Cutting and Pasting — Restriction Enzymes and Recombinant DNA",
 51: "Sanger's Ladders — The First Way to Read DNA",
 52: "Copying Without a Cell — The Polymerase Chain Reaction",
 53: "The Fingerprint — DNA as Evidence",
 54: "Fast, Cheap and Everywhere — The Sequencing Revolution",
 55: "Scissors From Bacteria — How CRISPR Became a Tool",
 56: "The First Cures — Gene Therapy Arrives",
 57: "Writing From Scratch — Synthetic DNA, Vaccines and Proteins",
 58: "Reading the Dead — Ancient DNA and the Neanderthals",
 59: "Dolly, 5 July 1996 — The Sheep From a Single Cell",
 60: "What a Clone Is and Isn't — Pets, Livestock and What Goes Wrong",
 61: "The Human Question — Cloning, Stem Cells and a Lecture in Hong Kong",
 62: "Ten Thousand Years of Editing — Domestication and Breeding",
 63: "The Tomato That Didn't Rot — The First Engineered Crops",
 64: "Animals on the Menu — Engineered and Cloned Livestock",
 65: "What Is Actually Risky — The Real Hazards of Engineered Farming",
 66: "Three Billion Letters, One Race — The Human Genome Project",
 67: "What the Genome Turned Out to Say — Gene Counts, Gaps and the Pangenome",
 68: "Biobanks and the Million — Common Disease at Population Scale",
 69: "The Spit Kit — What a Consumer Test Reads",
 70: "What a Genome Can Tell You — Risk Genes, Families and Drugs",
 71: "What It Cannot Tell You — Small Effects and Chance",
 72: "Who Else Is Reading — Police, Insurers and States",
 73: "Fixing What Is Broken — Editing Patients",
 74: "The Line We Said We Would Not Cross — Editing Embryos",
 75: "Enhancement — Better Humans, and the Accounting",
 76: "The Next Hundred Years — A Forecast to 2126",
}
