# -*- coding: utf-8 -*-
"""Authored text and data for the Math, Actually build."""
AUTHOR = 'Lothar J. Musiol'

VOLUMES = {
 1: dict(subtitle='From Arithmetic to Calculus', chapters=(1, 12),
         keywords='arithmetic; algebra; functions; geometry; trigonometry; logarithms; vectors; limits; calculus',
         blurb='Counting and number theory, algebra, functions and graphs, coordinates, Euclidean geometry, trigonometry, logarithms, systems of equations, vectors, limits, the derivative, and the integral. Chapters 1–12; it reads on its own through single-variable calculus.'),
 2: dict(subtitle='From Multivariable Calculus to Set Theory & Logic', chapters=(13, 25),
         keywords='multivariable calculus; vector calculus; series; Fourier; Laplace; linear algebra; complex analysis; set theory',
         blurb='Multivariable functions and calculus, vector calculus, series, Fourier and Laplace transforms, integral geometry, matrices, linear algebra, analytic geometry, complex analysis, counting, and set theory and logic. Chapters 13–25.'),
 3: dict(subtitle='From Differential Equations to Abstract Algebra', chapters=(26, 37),
         keywords='differential equations; PDE; optimization; numerical methods; differential geometry; topology; manifolds; functional analysis; measure theory; abstract algebra',
         blurb='Differential and integro-differential equations, partial differential equations, optimization and the calculus of variations, numerical methods, differential geometry, topology, advanced integral geometry, tensors and manifolds, functional analysis, measure theory, and abstract algebra. Chapters 26–37.'),
 4: dict(subtitle='From Category Theory to the Frontier', chapters=(38, 50),
         keywords='category theory; information theory; wavelets; game theory; statistics; probability; control theory; chaos; mathematical physics; modeling',
         blurb='Category theory, information theory, wavelets, game theory, statistics and probability, computational geometry, control theory, dynamical systems and chaos, mathematical physics, advanced optimization and numerical methods, and mathematical modeling. Chapters 38–50.'),
}

CHAPTER_TITLE_FIX = {50: 'Where Mathematics Meets the World'}

TOPIC_OVERRIDE = {}

ALSO_BY = ('Also by Lothar J. Musiol: *Physics, Actually*, the companion series on the physical world, '
           'and *Quantum, Actually*, on the quantum world. Every title is listed on the Also by Lothar J. Musiol '
           'page at the back of this volume.')

# Back matter: the canonical 'Also by Lothar J. Musiol' list (same in every book; see
# notes/ALSO_BY - canonical list.md at the repo root). Titles as on each master's title page.
ALSO_BY_HEADING = 'Also by Lothar J. Musiol'
ALSO_BY_LIST = [
    ('Physics, Actually', [
        'Physics, Actually, Volume 1: Motion, Forces, Time, and Relativity',
        'Physics, Actually, Volume 2: Gravity, Cosmology, and the Limits of Spacetime',
        'Physics, Actually, Volume 3: The Standard Model, Chaos, and the Edge of Knowledge',
        'Life, Actually: From the First Cell to the Edited Genome and the Search for Life Elsewhere',
    ]),
    ('Math, Actually', [
        'Math, Actually, Volume 1: From Arithmetic to Calculus',
        'Math, Actually, Volume 2: From Multivariable Calculus to Set Theory & Logic',
        'Math, Actually, Volume 3: From Differential Equations to Abstract Algebra',
        'Math, Actually, Volume 4: From Category Theory to the Frontier',
    ]),
    ('Quantum, Actually', [
        'Quantum, Actually, Volume 1: Questions and Answers from the Double Slit to the Superconducting Wire',
        'Quantum, Actually, Volume 2: A QED Course',
    ]),
    ('Science Sparks', [
        'Science Sparks: Physics, Life, and Mathematics — The Same Few Rules, Told in Highlights',
    ]),
    ('Look First', [
        'Look First, Volume 1: The Universe Has No Now',
        'Look First, Volume 2: A Trip Is Not a New Life',
    ]),
    ('Electrical Engineering Series', [
        'Foundations of Electronics (Book 1)',
        'Circuits, Components, and Control (Book 2)',
        'Semiconductor Physics and Devices (Book 3)',
        'RF, Microwave, and Transceivers (Book 4)',
        'Communications, Wireless, and SDR (Book 5)',
        'Power and Energy (Book 6)',
        'Packaging, Layout, EMC, and Test (Book 7)',
    ]),
    ('History', [
        "The Dolphins' View of History",
    ]),
    ('Fiction', [
        "The Murder That Hadn't Happened Yet (The Relativistic Investigation Bureau, Book 1)",
        'The Warning That Was Sent Too Late (The Relativistic Investigation Bureau, Book 2)',
        'Schrödinger’s Paperwork (Lolly Wren’s Curious Science Adventures, Book 1)',
        'The Permitted Options (Lolly Wren’s Curious Science Adventures, Book 2)',
        'Protocol Flamingo (The Invasion Storybooks, Book 1), as George Herbert Fontaine',
    ]),
    ('How-To', [
        'Your First Book That Sells',
        'Your First YouTube Channel That Rocks',
    ]),
]

def front_titles(vol):
    return ['Preface'] if vol == 1 else ['About This Volume']

def preface(vol):
    if vol == 1:
        return [('h1', 'Preface'),
 ('p', 'Welcome to *Math, Actually*. This is one book about mathematics, published as four volumes because no single spine could hold it: fifty chapters, from counting to the research frontier, written to be read in order or dipped into where you need them. The chapters began as separate manuscripts, each once content to stand alone on a shelf with its own index and its own faintly apologetic preface. They have been joined into one continuous text. Where one book used to end with a full stop and a wave goodbye, a chapter now hands its ideas straight to the next. Mathematics was never a row of unrelated courses, and pretending otherwise, one marketing budget per course, was a small and forgivable lie that has now been tidied up.'),
 ('p', 'The reason for doing it this way is that mathematics is a single connected structure pretending, for administrative convenience, to be several hundred unconnected ones. You cannot do calculus without algebra underneath it; you cannot do functional analysis without calculus, linear algebra, and a worrying amount of measure theory beneath that. Splitting these into fifty standalone books was good for the shelf and bad for the truth. Each idea in this series rests on ideas met earlier, and the text says so, with a link, every time it leans on one.'),
 ('p', 'How you read it is entirely up to you, and I say this as someone who has spent an unreasonable fraction of one career telling undergraduates how to read things. You may start at Chapter 1, with arithmetic — genuinely, properly, from the beginning, counting on your fingers if it comes to that — and read straight through to the mathematical physics and applied modeling at the end of Volume 4. That is the recommended route for anyone with patience, several free years, and no pressing deadline. It is also the route that makes each new chapter easy, because nothing is asked of you before it has been built.'),
 ('p', 'Alternatively — and this is the route most people will take, so let us not pretend otherwise — you may go directly to the chapter you need. Revising trigonometry before an exam? Chapter 6. Trying to remember what a Fourier transform is for, as opposed to what it is? Chapter 17. Wandered in from an engineering problem and need control theory by Tuesday? Chapter 45, and good luck. Every chapter tells you at the start what it assumes, and every section that uses an earlier idea links back to the place where that idea was introduced, so dipping in does not feel like arriving at a dinner party in the middle of an argument nobody explained.'),
 ('p', 'The layout is simple. Each chapter covers one broad territory — arithmetic, geometry, topology, and so on — and each section within it covers one idea: factoring, the chain rule, compactness. Sections are numbered by chapter, so Section 11.4 is the fourth section of Chapter 11. Some sections are short and get you in and out in a few paragraphs. Others — measure theory, I am looking at you — run rather longer than their titles suggest, and I can only apologize on behalf of the subject, not the author.'),
 ('p', 'I should confess that the later chapters contain ideas that took the human species several centuries and a fair number of nervous breakdowns to work out, and that I have compressed them into sections you can read over a cup of tea. This is either a great service to civilization or a mild insult to the mathematicians who did the actual suffering, and I have chosen not to dwell on which. Infinity in particular gets a great deal of attention, and I will say now what I will say again later at greater length: it does not behave, it does not apologize, and it has outlasted every mathematician who has ever tried to tame it.'),
 ('p', 'You will find, at regular intervals, worked examples — proper ones, with real numbers where real numbers will do, and honest concrete instances where the idea is too structural for arithmetic to touch. This is not decoration. An idea you cannot compute with is an idea you do not yet own, however elegantly you can recite it at a dinner party. Every one of these examples has been checked by hand, more than once, because a mathematics book that gets its own arithmetic wrong is a special and particular kind of disgrace.'),
 ('p', 'Every section follows the same order. It opens in plain language — what the idea is, why anyone wanted it, and what it feels like — before any formula appears. Then come the definitions and equations, and then the worked examples that put them to use. What follows is not a shortcut through mathematics; there isn’t one, whatever the adverts for certain revision guides may imply. It is, I hope, an honest route, with the steps cut small and nothing left unexplained. Chapter 1 starts, appropriately enough, with counting.'),
        ]
    prev = {2: 'Volume 1 (Chapters 1–12) runs from arithmetic to single-variable calculus and holds the full preface.',
            3: 'Volume 1 (Chapters 1–12) runs from arithmetic to single-variable calculus and holds the full preface; Volume 2 (Chapters 13–25) extends calculus to many variables and adds transforms, linear algebra, complex analysis, and the foundations of mathematics.',
            4: 'Volume 1 (Chapters 1–12) begins at arithmetic and holds the full preface; Volume 2 (Chapters 13–25) extends calculus to many variables and lays the foundations in set theory and logic; Volume 3 (Chapters 26–37) covers differential equations, geometry, analysis, and abstract structure.'}[vol]
    this = {2: 'This volume covers Chapters 13 through 25: multivariable and vector calculus, series and integral transforms, matrices and linear algebra, analytic and integral geometry, complex analysis, counting and discrete mathematics, and set theory and logic. Thirteen chapters that take everything Volume 1 built in one variable and generalize it — more dimensions, more structure, and, by the end, a first proper look at the foundations mathematics itself stands on.',
            3: 'This volume covers Chapters 26 through 37: differential, integro-differential, and partial differential equations; optimization and the calculus of variations; numerical methods; differential geometry, topology, and advanced integral geometry; tensors and manifolds; functional analysis; measure theory; and abstract algebra. Twelve chapters about the equations that describe change, and the increasingly abstract structures mathematicians built to solve, generalize, and finally justify them.',
            4: 'This volume covers Chapters 38 through 50: category theory; information theory; wavelets and signal analysis; game theory and decision mathematics; statistics and probability, in their standard and advanced forms; computational geometry; control theory; dynamical systems and chaos; mathematical physics; advanced optimization; advanced numerical methods; and mathematical modeling. Thirteen chapters, from the most abstract structures in the whole series to the discipline that points all of it back at the physical world.'}[vol]
    link = {2: 'Volume 1 ended with the integral. This volume opens by asking what happens to the derivative and the integral when a function depends on more than one number, and it closes with the logic and set theory on which every earlier chapter quietly relied. Volume 3 takes up differential equations, optimization, and the geometry that holds them together.',
            3: 'Volume 2 ended with set theory and logic, quietly underwriting everything before it. This volume opens with differential equations, which put the calculus of Volumes 1 and 2 to work on change itself, and it closes with abstract algebra. Volume 4 picks up where abstract algebra leaves off, with category theory, and continues to the research frontier.',
            4: 'Volume 3 ended with abstract algebra. This volume opens with category theory, the language that describes what all of those structures have in common, and it closes where the series has been heading from the first page: mathematics put to work on the world.'}[vol]
    return [('h1', 'About This Volume'),
            ('p', f'This is Volume {vol} of *Math, Actually*, one continuous fifty-chapter book about mathematics published in four volumes. {prev} If this is your first volume, the short notes that follow explain how the book is organized and where its foundations are; references to earlier volumes are given as a topic name with its volume, for example “Limits (Volume 1)”.'),
            ('p', this), ('p', link)]

def organized(vol):
    return [('h1', 'How This Book Is Organized'),
 ('p', 'The fifty chapters of *Math, Actually* run continuously across the four volumes, so Chapter 13 opens Volume 2 and Chapter 50 closes Volume 4. Each chapter is one broad territory of mathematics. Each section within a chapter is one idea, numbered by its chapter: Section 6.3 is the third section of Chapter 6. Each chapter ends with Check Your Understanding questions and a set of Problems; their answers are at the back of the volume.'),
 ('p', 'Whenever a section uses an idea from somewhere else, it names that section by its topic. Inside this volume the name is a link: follow it and you land on the section, and the Back button of your reader brings you home again. An idea from another volume cannot be linked across files, so it is named with its volume instead — “Limits (Volume 1)” — and the Subject Index of that volume will find it.'),
 ('p', 'Every section is built in the same order. It opens in plain language: what the idea is, why it matters, and what it feels like, usually with numbers you can check by hand. The definitions and formulas come next, once you have seen why they are needed. The worked examples follow and put the formulas to use.'),
 ('p', 'One more convention, purely visual. Worked examples appear in shaded boxes rather than running paragraphs, so that your eye can find them again on a later skim. A blue box marks an example that works through actual numbers, or through the general case when numbers would not illuminate anything — either way, one clean argument from start to finish. A purple box marks the rarer case where you get both: the concrete instance and the general pattern beside it, on the theory that seeing the same idea twice, once with numbers and once without, is worth the extra half-page far more often than authors like to admit.'),
    ]

def foundations(vol):
    return [('h1', 'Where the Foundations Are'),
 ('p', 'One structural confession, best made early. The book begins with counting, because that is where a human being begins. But the logical foundations of mathematics — the axioms of set theory, the rules of inference, the machinery that says what a proof is — are not in Chapter 1. They are in Chapter 25, at the end of Volume 2, which is an odd place to put a foundation.'),
 ('p', 'This is deliberate, and it is not a compromise. Mathematics was not discovered in logical order. Counting is some tens of thousands of years old; the axioms that justify it were written down in the 1920s. Children learn arithmetic long before they learn what a set is, and the ones who go on to learn what a set is do not thereby discover that their arithmetic was wrong. The foundations were laid underneath a subject that was already well established and doing perfectly well.'),
 ('p', 'So you do not need Chapter 25 to read the chapters before it. You will want to read it eventually, for the same reason anyone eventually looks at foundations: not because anything is falling down, but because you have started to wonder what is holding it all up. Readers who prefer their logic first are welcome to read Chapter 25 early. It assumes very little and says so.'),
    ]

EPILOGUE_TITLE = {1: 'Epilogue — Halfway Through the Calculus', 2: 'Epilogue — Between Volumes',
                  3: 'Epilogue — Between Volumes', 4: 'Epilogue — Looking Back over the Whole'}
EPILOGUE = {
 1: ['This is a pause, not the end. The book continues in Volume 2.',
     'It is worth pausing here anyway. You have read twelve chapters, and they are the ones everything later leans on — which means the effort you have already spent is about to start paying compound interest. Mathematics punishes the reader who meets an idea cold and rewards the one who has met it before, however briefly. You now have a great many such half-memories, and every one of them is a hook that later reading can hang on.',
     'Before going on, consider going back to the one chapter that nagged at you. A second reading of mathematics is worth roughly four first readings, and the difference is almost entirely that you are no longer spending effort on the vocabulary.',
     'When you are ready, Volume 2, *From Multivariable Calculus to Set Theory & Logic*, takes up functions of several variables, the transforms, linear algebra, complex analysis, and the foundations in set theory and logic. It begins exactly where Chapter 12 stopped: with the integral, now asked to work in more than one dimension.'],
 2: ['This is a pause, not the end. The book continues in Volume 3.',
     'You have now read twenty-five chapters. Calculus has been taken into many dimensions, linear algebra has turned systems of equations into geometry, complex analysis has shown how much a single derivative can know, and the last chapter dug down to the logic underneath all of it. That is the toolkit almost every later chapter will reach for.',
     'Before going on, consider rereading the chapter that resisted you. Linear algebra in particular repays a second pass more generously than almost anything else in mathematics.',
     'When you are ready, Volume 3, *From Differential Equations to Abstract Algebra*, opens with differential equations — calculus put to work on change itself — and moves through optimization, geometry, analysis, and measure theory to abstract algebra.'],
 3: ['This is a pause, not the end. The book continues in Volume 4.',
     'Thirty-seven chapters are behind you. Differential equations, optimization, numerical methods, geometry, topology, functional analysis, measure theory, and abstract algebra are the working language of most of modern mathematics, and you have now met all of them at least once.',
     'Before going on, consider rereading the chapter that resisted you. Measure theory and functional analysis in particular read very differently the second time, once you know where they are going.',
     'When you are ready, Volume 4, *From Category Theory to the Frontier*, opens with category theory — the language that describes what all of these structures have in common — and ends with mathematics put to work on the world.'],
 4: ['This is the end of the book, and it is worth a moment.',
     'Fifty chapters ago you were counting sheep with tally marks. Since then you have built the numbers, learned to solve for what you do not know, measured change and accumulation, taken calculus into many dimensions, solved the equations of change, met the abstract structures that organize all of it, and finally turned the whole apparatus back on the world — on signals, games, data, machines, and physical law. Nothing in that sequence was assumed before it had been built.',
     'None of it is finished. Every chapter of this book is the front edge of a field that is still growing, and the Further Reading appendix names the books that will take you further in any direction you choose. The point of a survey was never to be the last word. It was to make sure that when you open one of those books, nothing in it is wholly unfamiliar.',
     'Go back to the chapter that surprised you most. Then pick up a pencil.'],
}
CLOSING = {
 1: ['If this volume made you see something ordinary — a remainder, a slope, an area — a little differently, it did its job. Volume 2 is waiting when you are.', 'Thank you for reading.'],
 2: ['If this volume made you see something ordinary — a weather map, a sound wave, a set — a little differently, it did its job. Volume 3 is waiting when you are.', 'Thank you for reading.'],
 3: ['If this volume made you see something ordinary — a cooling cup of tea, a soap film, a symmetry — a little differently, it did its job. Volume 4 is waiting when you are.', 'Thank you for reading.'],
 4: ['If this book made you see something ordinary — a coin toss, a thermostat, a weather forecast — a little differently, it did its job. *Physics, Actually* and *Life, Actually* take the same approach to the physical world and to living things.', 'Thank you for reading all fifty chapters.'],
}

# On-ramp paragraphs: one per section listed in notes/Math, Actually - Sections Needing On-ramps.md.
# Inserted by build_math_actually.insert_onramps (step 8c).
ONRAMPS = {
    'Section 1.5': 'Some numbers share out cleanly and some refuse. Forty-two sweets split evenly among six children, seven each, with nothing left over; try five children and two sweets remain, and somebody cries. That clean sharing is divisibility, and it is the first question worth asking of any whole number: what goes into it evenly? Push the question far enough and you meet numbers that nothing divides except 1 and themselves, such as 2, 3, 5, 7 and 11. These are the primes. Every other whole number is built from them by multiplication, the way molecules are built from atoms, which is why they turn up everywhere from school worksheets to the encryption guarding your bank card.',
    'Section 1.7': 'Some quantities go round in circles. A clock never shows fifteen o’clock: wait five hours after ten and the hand lands on three, because after twelve it starts again. Days of the week behave the same way, so nine days after a Monday is a Wednesday, and so do odometers rolling over and the last digit of a long sum. In each case we have quietly stopped caring about the full number and kept only the remainder after dividing by the length of the cycle. Modular arithmetic is the habit of doing exactly that on purpose, and it turns out to be strong enough to check credit-card numbers and to build secret codes.',
    'Section 2.5': 'Throw a ball into the air and its height rises, peaks and falls back along a curve. Ask when it passes a particular height and the answer usually comes in two: once on the way up, once on the way down. That is the signature of a quadratic, an equation in which the unknown gets multiplied by itself. Linear equations have one answer; quadratics can have two, one or none, and the work lies in finding which. A small puzzle shows the flavour: which numbers give zero when you double their square, add three times the number and take away two? Both one half and minus two do, and this section gives three reliable ways to find them.',
    'Section 2.7': 'A lift that carries no more than 600 kilograms, a film for viewers at least twelve years old, a speed limit of 70: everyday rules are rarely about one exact number. They describe a whole range of acceptable values, and inequalities are the mathematics of ranges. Instead of asking which number makes a statement true, we ask which numbers do. Take “three more than twice a number is more than seven.” The number 3 works, giving nine; 2.5 works, giving eight; but 2 itself gives exactly seven and fails. The answer is every number greater than 2, a whole stretch of the number line rather than a single point.',
    'Section 3.6': 'Many processes come in stages. A shop takes money off a price and then adds tax; a recipe converts cups to grams and grams to calories. Each stage is a function, and feeding one straight into the next is composition: the output of the first becomes the input of the second. Order matters. Taking ten off 50 and then halving gives 20; halving first and then taking ten off gives 15. Running a process backwards is the other half of the story. If one machine triples a number and subtracts 2, turning 4 into 10, its inverse adds 2 and divides by 3, turning 10 straight back into 4.',
    'Section 4.3': 'How far is it from one corner of a city block to the opposite corner, as the crow flies? Walk three blocks east and four north and you have covered seven, but the straight line is shorter: five blocks, because three, four and five are the sides of a right triangle. Coordinates let us do this for any two points without a ruler. Subtract to find how far apart they are across, and how far apart up and down, then let Pythagoras finish the job. From the point (1, 2) to the point (4, 6) is three across and four up, so the gap is exactly 5. Finding the point halfway between them is easier still: average the coordinates.',
    'Section 5.5': 'Builders have used a knotted rope for thousands of years to get a square corner. Mark off lengths of 3, 4 and 5 units, pull the rope taut into a triangle, and the angle between the two shorter sides comes out exactly right. The reason is the most famous fact in geometry. In a right triangle, a square drawn on the longest side has the same area as the squares on the other two sides put together: 9 plus 16 makes 25. The fact also works in reverse, which is what the builders rely on, and it is the reason distances on a map, a screen or in space can be computed at all.',
    'Section 7.1': 'Doubling is deceptively quiet. A colony of 50 bacteria that doubles every hour has 100 after one hour, 200 after two and 1,600 after five: the same small step, repeated, with alarming results. Writing “double it five times” as a long row of twos gets tedious, so mathematicians invented a shorthand, a small raised number saying how many copies to multiply, and two to the fifth power is 32. A logarithm asks the reverse question: how many doublings does it take to reach a given size? Getting from 50 to 1,600 takes five. Exponents and logarithms are that question and its answer, seen from opposite ends.',
    'Section 7.3': 'Once a power is shorthand for repeated multiplication, a handful of rules follow from nothing more than counting. Three twos multiplied together, then two more, make five twos in a row: 8 times 4 is 32, which is two to the fifth. Squaring a cube takes three twos twice, six in all, so 8 squared is 64. Dividing cancels copies: 32 divided by 8 leaves two twos, which is 4. These are the laws of exponents, and they are worth knowing cold, because nearly every calculation with growth, interest, decibels or scientific notation leans on them, and because one tempting “law” that is not on the list catches people every year.',
    'Section 7.4': 'Ask “ten to what power gives a thousand?” and you have asked for a logarithm. The answer is 3, because a thousand is ten times ten times ten. In the same way, three squared is nine, so the logarithm of nine in base three is 2. A logarithm is simply the exponent you need, given the base and the result. That makes it the natural tool whenever the unknown sits up in the exponent: how many years until an investment doubles, how many halvings until a sample is safe. It also explains why the base must be positive and not 1, since a base of 1 can never grow into anything but 1.',
    'Section 7.5': 'Before calculators, astronomers multiplied enormous numbers by adding. The trick, published by John Napier in 1614, is that logarithms turn multiplication into addition. A hundred is ten to the power 2, a thousand is ten to the power 3, and their product, a hundred thousand, is ten to the power 2 plus 3, which is 5. Division becomes subtraction in the same way, and raising to a power becomes ordinary multiplication. Every rule in this section is one of the exponent laws from two sections back, read in reverse, and together they let you pull a complicated expression apart into pieces you can actually handle.',
    'Section 7.7': 'A picture tells you at a glance what a formula keeps to itself. Savings earning interest, a cooling cup of coffee, the brightness scale astronomers use for stars: each follows an exponential or a logarithmic curve, and recognising the shape is half of understanding the behaviour. The two curves are mirror images of each other. One starts almost flat and then climbs ever faster, doubling with every step to the right; the other shoots up at first and then rises ever more slowly, gaining just one for each doubling of its input. This section builds both pictures from a single small table of powers of 2, running from a quarter up to 8.',
    'Section 7.8': 'Some things change by the same proportion every step rather than by the same amount. A savings account grows by a fixed percentage each year; a radioactive sample loses half of itself in a fixed time, whatever its size. Carbon-14 has a half-life of 5,730 years, so 80 grams of it becomes 40 grams after 5,730 years and 20 grams after 11,460. Population growth, cooling coffee, compound interest and the decibel scale all follow the same pattern, and all yield to the tools of this chapter: exponentials to predict forward, logarithms to work out how long it takes. This section puts both to work on real questions.',
    'Section 10.3': 'Engineers live with tolerances. A machined shaft is specified as 10 millimetres, give or take 0.1, and the machinist’s job is to know how carefully to work so that the result lands inside that window. The precise definition of a limit is the same bargain. Someone names a tolerance around the target value, as small as they like, and you must answer with a closeness for the input that guarantees the output lands inside it. For the function that doubles a number and adds one, heading for 7 as the input heads for 3, a demanded tolerance of 0.1 is met by keeping the input within 0.05, and halving answers every tolerance anyone could name.',
    'Section 11.4': 'Working out every derivative from the definition would be like finding square roots by trial and error: possible, but nobody does it twice. Instead, a short list of ready-made results covers almost every function you will meet, from powers and roots to sines, cosines, exponentials and logarithms. The rule for powers is the workhorse: the curve of a number squared has, at any point, a slope of twice that number, so at 3 it climbs with slope 6. Sines have a neat rule of their own, with the cosine giving the slope, which is why at sixty degrees the sine curve rises at exactly one half. This section collects the list and shows where each entry comes from.',
    'Section 12.2': 'How do you measure the area of a field with one curved edge? Lay strips across it, treat each strip as a rectangle, add up the rectangles, then use thinner strips and do it again. The estimates creep toward the true answer, and the true answer is whatever they settle on as the strips become infinitely thin. Under the curve of a number squared, between 0 and 2, four strips half a unit wide give 3.75 if each is as tall as the curve at its right edge and 1.75 if it takes the height at its left edge. Both estimates close in on eight thirds, about 2.67. That procedure, made precise, is the definite integral.',
    'Section 13.2': 'A walker’s map does not show a mountain in three dimensions. It shows contour lines, each joining points at the same height, and with a little practice you can read peaks, valleys and passes straight off the flat page. Functions of two variables can be drawn the same way: the input is a position on the ground, the output is a height, and each level set is one contour line. Before drawing anything, though, we need to know where the function makes sense at all. A formula that takes the square root of one minus the squared distance from the centre only works within distance 1 of the centre, a disc of radius 1.',
    'Section 14.5': 'Carry a suitcase up three flights of stairs and back down again, and gravity has, on balance, done no work on it: whatever it took on the way up it returned on the way down, and the route you chose made no difference. Forces like that are called conservative, and they are exactly the ones that allow an energy account, a single number at each point, the potential, from which the force can be read off. Friction is the opposite. Drag a box round a room and back to where it started, and you have paid all the way. This section shows how to tell the two kinds apart and how to recover the potential when it exists.',
    'Section 14.7': 'A surveyor can find the area of an irregular plot without stepping inside it, simply by walking the boundary and keeping a running tally; a brass instrument called a planimeter does the same thing mechanically. Green’s theorem is the mathematics behind the trick: a total over a region equals a tally taken around its edge. It is the fundamental theorem of calculus moved up one dimension, where an integral over an interval was settled by the values at its two endpoints. As a test, walking once round an ellipse with half-widths 3 and 2 and adding up the right quantity along the way returns its area, six times pi, about 18.85, without visiting the interior.',
    'Section 15.2': 'Stand on a hillside and three questions come naturally. Which way is straight uphill, and how steep is it? If water is flowing past, is more of it leaving this spot than arriving? And would a small paddle wheel dropped here start to spin? Vector calculus answers the three questions with the gradient, the divergence and the curl. All three are built from the same partial derivatives, combined in different ways, and together they describe almost everything a field can do near a point. For a temperature or a height that depends on position, the gradient is an arrow pointing in the direction of fastest increase, and its length gives the rate of that increase.',
    'Section 15.3': 'Some combinations of operations always come to nothing. Wander over a hill and return to your starting point and your total change in height is zero, however you went; correspondingly, a slope field built from a height can never swirl. Water turning in a pure whirlpool has no source or drain anywhere; correspondingly, a field made purely of swirl never spreads out or bunches up. These facts become identities that hold for every field, alongside product rules much like those of single-variable calculus. They matter because they let physicists trade one description for another, most famously in electromagnetism, where one of them guarantees that magnetic field lines never begin or end.',
    'Section 16.5': 'An infinite polynomial would be of little use if you could not do arithmetic with it. Happily, inside the range where it converges, a power series can be added, multiplied, differentiated and integrated term by term, exactly as if it were an ordinary long polynomial. That turns a few known series into a factory for new ones. Multiply the geometric series, one plus x plus x squared and so on, by itself, collect like powers, and you get one plus two x plus three x squared plus four x cubed, and so on. At x equal to one half the geometric series adds up to 2, and the new series adds up to 4, its square, exactly as it should.',
    'Section 17.3': 'A graphic equaliser splits music into frequencies, lets you turn some up and others down, and then reassembles the sound. That only works because the splitting loses nothing: from the full list of frequency ingredients you can rebuild the original signal exactly. The inversion theorem says the Fourier transform has this property, and that its reverse is almost the same formula with a single sign flipped. Plancherel and Parseval add a second guarantee. The total energy of a signal, measured over time, equals its total energy measured across frequencies. Nothing is gained or lost in translation, which is why engineers can work in whichever description is easier and trust the answer in the other.',
    'Section 18.5': 'Real systems get switched on, switched off and struck. A heater is flicked on at noon and left running; a circuit sees its voltage jump from nothing to 12 volts; a bell is hit once with a hammer. Smooth formulas describe such events badly, so engineers use two idealised building blocks. The step is off until a chosen instant and on forever afterwards. The impulse is a blow so brief that only its total size matters, like a hammer tap delivering one unit of kick in no time at all. The Laplace transform handles both with almost no effort, which is a large part of the reason control engineers are so fond of it.',
    'Section 18.6': 'Stand in a room with an echo and clap once: what you hear is the clap followed by a dying tail. Speak continuously and what reaches you is every recent syllable overlaid with its own fading echo. That overlaying of an input with the system’s response to a single blow is convolution, and it describes any system with memory: a loudspeaker, a car’s suspension, a bloodstream absorbing a drug. A capacitor charging through a resistor is the cleanest example. Feed it a steady input and each instant’s contribution fades away exponentially, but the contributions pile up, so the output climbs smoothly toward its final value of 1 without ever overshooting.',
    'Section 18.8': 'Sometimes you do not need the whole answer, only how it starts or where it ends up. Will the motor settle at 1,500 revolutions per minute? Where does the tank level finish after the valve opens? The Laplace transform can answer such questions directly, reading the starting value and the final value off the transformed expression without ever converting back. It is a genuine shortcut, with one trap. A system that keeps oscillating forever, like a frictionless pendulum, has no final value at all, and the shortcut will cheerfully report a number anyway unless you first check that the system really settles. This section collects that shortcut and several more like it.',
    'Section 20.2': 'A table of sales, with shops down the side and products across the top, is a matrix, and some of its arithmetic is obvious. Add last month’s table to this month’s, entry by entry, and you have the two-month totals; double every entry and you have the forecast for a month twice as busy. Multiplication is the surprise. Multiplying a table of quantities by a table of prices gives revenue, and the rule that does it pairs each row of the first table with each column of the second. Because rows and columns play different roles, swapping the order usually changes the answer, and sometimes makes the product meaningless. Matrices are the first numbers you meet that refuse to commute.',
    'Section 20.3': 'Some actions can be undone and some cannot. Rotate a photograph by 30 degrees and you can rotate it back; squash it flat onto a line and the lost detail is gone for good. Matrices describe actions like these, and the ones that can be undone are called invertible. The undoing matrix is the inverse, and an action followed by its inverse leaves everything exactly where it was, which is what the identity matrix does: the matrix version of multiplying by 1. For a stretch that doubles every length, the inverse halves every length. This section shows how to tell whether an inverse exists and how to compute it, one elementary step at a time.',
    'Section 20.4': 'A matrix transforms the plane, stretching, shearing and sometimes flipping it, and a single number tells you how much it scales areas. Send the two unit arrows along the axes to the arrows (3, 1) and (1, 2), and the unit square becomes a parallelogram of area 5; every shape in the plane has its area multiplied by 5 in the same move. That number is the determinant. When it is zero, the transformation has squashed the plane flat onto a line or a point, and nothing can undo it, which is why the determinant is the quickest test of whether a matrix has an inverse. Its sign records whether the transformation flips the plane over.',
    'Section 21.2': 'A set of directions is only useful if none of them is redundant. Tell someone to walk east, then north-east, and you have given two genuinely different instructions; add “walk two east and one north-east” and the extra instruction tells them nothing new. Directions with no redundancy are called linearly independent, and an independent set that still reaches everywhere is a basis, a minimal toolkit for describing every position. With the arrows one unit east and one unit north-east, the point (5, 3) is reached by two steps of the first and three of the second. Every basis of a space has the same number of arrows, and that number is its dimension.',
    'Section 21.3': 'Some transformations treat sums and scaled copies politely: transform two arrows and add the results, and you get the same as adding first and transforming afterwards. Rotations, reflections and stretches all behave this way, and they are called linear maps. Because they are so well behaved, a linear map is completely determined by what it does to a handful of basis arrows, and that information fits in a matrix. Reflect the plane in its diagonal line, for instance, and every point swaps its two coordinates, so (2, 5) lands on (5, 2); the east and north arrows trade places, and that fact alone pins down the whole map. Change the basis and the same map wears a different matrix.',
    'Section 21.5': 'Stretch a sheet of rubber eastward and most arrows drawn on it change direction as well as length, tilting toward the east. A few do not. An arrow pointing exactly east only gets longer, and an arrow pointing exactly north, across the stretch, stays exactly as it was. Those special directions are eigenvectors, and the factor by which each one is stretched is its eigenvalue: 3 for the east arrow if the stretch triples lengths, 1 for the north arrow. Find these directions and a complicated transformation becomes simple, because along each of them it is just multiplication by a number. That is why eigenvalues sit underneath vibration analysis, population models and quantum mechanics.',
    'Section 21.6': 'Vector spaces as defined so far know how to add and scale, but nothing about length or angle. An inner product brings both back. It is a rule that takes two vectors and returns one number, with the ordinary dot product as the model: for the arrows (3, 4) and (4, −3) it gives 3 times 4 plus 4 times minus 3, which is zero, so the two arrows meet at a right angle. The same rule applied to an arrow and itself gives its length squared, here 25, so each arrow has length 5. With length and angle restored, we can build perpendicular coordinate systems in any such space, and perpendicular systems make almost every calculation easier.',
    'Section 22.2': 'A straight line can be pinned down in several ways, and which one you use depends on what you are given. Two points will do; so will one point and a direction of travel; so will a slope and the place where the line crosses an axis. Each description leads to its own equation, and all of them describe the same set of points. Take the line through (1, 2) and (4, 8). Going from the first point to the second moves 3 across and 6 up, so every step of 1 across climbs 2: the direction (1, 2), or a slope of 2. Planes in space work the same way, with a second direction or a single perpendicular arrow.',
    'Section 22.3': 'Distance, angle and shadow are what a ruler, a protractor and the midday sun measure, and vectors handle all three with the same few operations. The distance between two points is the length of the arrow joining them: from (1, 2, 3) to (4, 6, 3) the arrow runs three along, four across and nothing up, so the distance is 5, Pythagoras in three dimensions. The angle between two arrows comes from the dot product. The shadow, or projection, is the part of one arrow lying along another, the way a ladder casts a shadow on the ground, and the leftover part stands at right angles to it. Together they settle every nearest-point question in this section.',
    'Section 22.4': 'A circle is the easiest shape there is to describe in words: every point at the same distance from a centre. A compass draws one by holding that distance fixed. Coordinates turn the description straight into an equation, using the distance formula from the previous section. The circle with centre (2, −3) and radius 5 passes through the point (5, 1), because that point lies 3 across and 4 up from the centre, and 3, 4, 5 is a right triangle. A sphere is the same idea in three dimensions, and stretching a sphere by different amounts along each axis, or bending it open, produces the ellipsoids, paraboloids and saddles known as the simple quadric surfaces.',
    'Section 22.5': 'Slice an ice-cream cone with a knife and the cut edge takes one of a few shapes. Cut at a gentle slant and you get an oval, an ellipse; tilt the knife until it runs parallel to the side of the cone and you get a parabola; tilt it further, on a double cone, and you cut both halves, getting the two branches of a hyperbola. Planets travel on ellipses, thrown balls on parabolas and some comets on hyperbolas. An ellipse 10 units long and 6 units wide has its two focal points 8 units apart, which makes it fairly elongated. This section shows how to tell the three curves apart from a single number computed from their equation.',
    'Section 22.6': 'Draw an ellipse at a slant and its equation acquires an awkward mixed term, a piece in which the two coordinates are multiplied together. The curve itself is perfectly ordinary; it has simply been rotated away from the axes. Tilt your head to line up with the curve’s own axes and the mixed term disappears, leaving an equation you can read at a glance. This section turns that head-tilt into a procedure. The tilted curve given by five x squared, plus four x times y, plus eight y squared, equal to 36, turns out to be an ellipse whose own half-axes are 3 and 2 long, once you look along the right directions.',
    'Section 23.6': 'Some integrals along the real line resist every technique from first-year calculus, yet give way after a detour through the complex plane. The idea is to close the path into a loop and use a remarkable fact: the integral around a loop depends only on the troublesome points trapped inside it, each of which contributes a single number called its residue. An integral over a whole curve shrinks to a short sum. The classic case is the area under the curve one over one plus x squared, across the entire real line. Closing the path with a huge semicircle traps just one troublesome point, at i, and the answer, pi, drops out in a couple of lines.',
    'Section 23.8': 'A metal plate held at fixed temperatures around its edge settles, after a while, into a steady pattern of temperature inside. That pattern has a striking property: the temperature at any point is exactly the average of the temperatures on any circle drawn around it, so the hottest and coldest spots can only lie on the edge, never in the interior. Functions with this averaging property are called harmonic, and they also describe electric potential in empty space. The real part of any well-behaved complex function is harmonic. For the saddle that comes from squaring a complex number, the average round any circle centred at the origin is zero, its value at the centre.',
    'Section 24.2': 'Counting sounds like the easiest thing in mathematics until the things being counted are arrangements rather than objects. How many meals can be ordered from a short menu, how many eight-character passwords exist, how many ways can a committee of three be chosen from ten people? Listing them soon becomes hopeless: there are 120 possible committees, and the passwords run to hundreds of trillions once capitals, small letters and digits are allowed. A few principles do the work instead. Multiply when choices are made one after another, add when they are alternatives, and divide out orderings you do not care about. Generating functions, at the end of the section, pack a whole counting problem into a single expression.',
    'Section 24.4': 'Strip a road map down to its essentials and you are left with towns and the roads between them. Strip down a social network and you have people and friendships; a molecule, atoms and bonds; a project plan, tasks and dependencies. In every case the useful information is simply which things are connected to which, and that is all a graph records: dots, called vertices, and lines between them, called edges. The geometry is thrown away, so the same tools work for all of them. Finding the fewest roads from one town to every other, for example, is done by spreading outward from the start one step at a time, and the roads used form a tree.',
    'Section 26.1': 'A differential equation is a rule saying how something changes from its present state, and the hope is that the present settles the whole future: drop a ball from a known height at a known speed and its path is fixed. Usually that hope is justified, but not always. Take a quantity that starts at zero and grows at a rate equal to the cube root of its current value. It can sit at zero forever, and it can equally well start growing at once, and both obey the rule. Two futures from one present is bad news for anyone trying to predict anything. This section pins down the extra smoothness condition that rules such double futures out.',
    'Section 26.5': 'Most of the equations met so far have no memory: the rate at which a cup of tea cools depends only on how hot it is now. Many real systems are not like that. A loan balance depends on every payment ever made, a population on births many years back, a stretched polymer on its whole history of stretching. Equations for such systems put a rate of change and a running total over the past, an integral, side by side. These are integro-differential equations. They can look forbidding, but the past enters in a structured way, as a weighted sum of earlier values, and the same patient step-by-step approximations used for ordinary equations still close in on the answer.',
    'Section 26.8': 'When you adjust a shower, the water reaching your head reflects where you set the tap a couple of seconds ago, not where it is now, and that lag is why people swing from too cold to too hot and back. Systems like this are governed by delay equations, in which the rate of change depends on the state at an earlier time as well as on the present one. Blood-cell production, predator and prey populations and network traffic control all behave this way. The consequence is surprising: to predict the future you need not just the present value but the whole recent stretch of history, and the solution is built forward one delay-length at a time.',
    'Section 27.3': 'Sound waves, heat spreading along a metal bar and a soap film stretched on a wire frame are all described by second-order partial differential equations, yet they behave in completely different ways. Waves travel at a finite speed and keep their sharp edges; heat spreads everywhere at once and smooths every edge away; the soap film is settled all at once by its boundary, with no time involved at all. Remarkably, which of these three personalities an equation has can be read off its coefficients by the same test that tells a circle, a parabola and a hyperbola apart. The three names, elliptic, parabolic and hyperbolic, are borrowed straight from the conic sections.',
    'Section 27.7': 'Pluck a guitar string and it vibrates in a blend of simple patterns: the whole string swinging as one arch, the two halves swinging in opposition, then three parts, and so on, each pattern with its own pitch. Separation of variables turns that observation into a method. Guess that the solution is a shape in space multiplied by a rhythm in time, find the possible shapes and rhythms separately, and then add up enough of them to match how the string started. For a string first pulled into a smooth arch, just two such sine patterns already reproduce the starting shape to within 0.6 per cent at its highest point.',
    'Section 27.8': 'Press on a taut trampoline with one finger and the surface dips around that point. Press with a whole hand, or scatter sand across it, and the shape you get is simply the sum of single-finger dips, one for every point where weight is applied. That single-finger response is the Green’s function, and once you know it, any load can be handled by adding up responses. For a string held fixed at both ends, the response to a push three tenths of the way along is a tent, rising in a straight line to that point and falling in a straight line beyond it. The section adds two more ways to study a solution never written down.',
    'Section 28.4': 'Ordinary calculus finds the number that makes a quantity smallest. The calculus of variations finds the whole curve that does. Which path between two points is shortest? Which shape of hanging chain has the lowest centre of gravity? Which curve, spun around an axis, makes the soap film of least area? Each question has a single number to minimise, a length, an energy or an area, but the unknown is an entire function. The trick is to wiggle a candidate curve slightly and demand that, to first order, nothing improves, just as a derivative is zero at a minimum. That demand produces a differential equation, and for the soap film its solution is the hyperbolic cosine, the catenary.',
    'Section 28.7': 'Throw a ball and it follows a parabola, but the ball does not work out its forces step by step. There is another way to describe its path: of all the routes it could take between where it starts and where it lands, in the time it takes, the real one makes a certain total, the action, stationary. The action adds up, moment by moment, the energy of motion minus the energy of position. From this single principle all of Newton’s mechanics follows, and it extends cleanly to planets, pendulums and light. For a mass on a spring, the principle returns a steady oscillation, with energy passing back and forth between spring and motion while the total stays fixed.',
    'Section 29.6': 'Most differential equations met in practice have no solution formula, so we compute the solution instead, one small step at a time: use the current rate of change to estimate where things will be a moment later, move there, and repeat. The danger is that small errors pile up. Take something that grows at a rate equal to its own size, starting from 1. Stepping forward a tenth at a time with the simplest rule gives 1.1, then 1.21, then 1.331, while the true value after those three steps is about 1.350. Cleverer rules sample the rate several times per step and do dramatically better; this section shows how, and when even they need special care.',
    'Section 29.7': 'To simulate heat spreading through a metal rod, a computer chops the rod into short pieces and time into short ticks, and at every tick it updates each piece from its neighbours: a piece hotter than the average of its two neighbours cools, one that is colder warms. It is a simple recipe and it works, but only if the tick is short enough compared with the size of the pieces. Take too long a tick and the method overcorrects; a hot spot can produce a temperature colder than anything present at the start, and the errors then grow without limit. This section explains that trade-off and the more expensive methods that avoid it entirely.',
    'Section 30.2': 'A workshop makes two products from limited supplies of labour, material and machine time, and wants the greatest profit. The profit is a simple sum, so much per item of each product, and each limit is a simple inequality. Problems of exactly this kind are linear programmes, and they are the best-understood optimisation problems there are. Drawn on paper, the allowed production plans form a region with straight edges, here a pentagon, and the best plan always sits at one of its corners. The simplex method exploits that by walking from corner to better corner along the edges; in this section’s example it reaches the best corner after visiting just four of the five.',
    'Section 30.3': 'Finding the lowest point of a landscape in thick fog is the everyday picture of optimisation. The obvious strategy is to feel which way the ground slopes most steeply, take a step downhill and repeat. This is gradient descent, and it underlies the training of almost every machine-learning system in use today. It has one weakness. In a long, narrow valley the steepest direction points mostly across the valley rather than along it, so you zigzag from wall to wall and progress slowly. A bowl ten times steeper in one direction than the other is enough to show it. Newton’s method, which also uses the curvature of the ground, reaches the bottom of such a bowl in a single step.',
    'Section 30.6': 'Suppose a planner claims that a delivery schedule costing 120 pounds is the cheapest possible. How could you check without trying every other schedule? Duality supplies the answer. Alongside every minimisation problem sits a second problem, the dual, whose values are guaranteed never to exceed the best value of the first. If someone also hands you a dual value of 120, the matter is settled, because no schedule can beat a figure that a lower bound already matches. In good cases, including every linear programme and every convex problem meeting a mild condition, the two problems meet exactly, and the dual’s solution also tells you what each constraint is worth: the price of loosening it.',
    'Section 30.8': 'Sometimes the thing you want to optimise is not a formula at all. It might be a crash simulation that takes an hour per run, a wind-tunnel test, or a chemical process you can only measure; there is no derivative to compute, and every evaluation is expensive. At other times there is a formula, but it is a sum over a billion data points, and computing its exact slope at every step would take forever. This section gathers the methods built for these situations: comparing a few trial points and moving the worst one, estimating slopes from the readings themselves, and following a cheap, noisy slope estimate computed from a small random sample of the data.',
    'Section 32.7': 'A rubber band on a table can be slid into any other loop on the table. Put it round a post and it cannot be removed without cutting it or lifting it over the top. That difference is exactly what topology measures with loops. Two loops count as the same if one can be deformed into the other without breaking, and the different kinds of loop that remain, together with the rule for following one loop after another, form the fundamental group of a space. A flat disc has only one kind of loop. A doughnut’s surface has loops that go round the hole, loops that go through it, and combinations, so the group detects its holes.',
    'Section 35.3': 'A matrix stretches some directions more than others, and for many purposes the number that matters is the worst case: what is the largest factor by which it can lengthen any arrow? A transformation that turns the unit circle into an ellipse with half-axes 3 and 1 can lengthen an arrow by at most 3, so its operator norm is 3. In infinite-dimensional spaces, where the vectors are functions and the transformations include integrals and filters, such a worst-case factor may or may not exist. The transformations where it does, the bounded operators, are the well-behaved ones, and this section studies them together with their duals, the measurements a space allows.',
    'Section 35.7': 'A symmetric matrix has a very convenient property: there is a set of perpendicular directions along which it simply stretches, and in those directions every calculation becomes multiplication by a number. The spectral theorem in this section carries that property into infinite dimensions, for a well-behaved class of operators called compact and self-adjoint. The vibrating string shows the payoff. Its natural modes are the sine waves that fit exactly between the fixed ends, with one, two, three or more humps, and any reasonable starting shape can be written as a sum of them. Each mode then simply oscillates at its own frequency, which is precisely the diagonalisation the theorem guarantees.',
    'Section 35.8': 'Differentiation is the most important operator in analysis, and it is badly behaved. A function can be tiny everywhere and still have an enormous derivative: a rapid wiggle one hundredth of a unit high, repeating ten thousand times per unit of length, never exceeds a hundredth in size, yet its slope reaches 100. Worse, perfectly reasonable functions such as the absolute value have a corner where no ordinary derivative exists. This section deals with both problems. It treats differentiation as an operator defined only on suitable functions, and it widens the meaning of derivative to a weak sense in which the absolute value’s derivative is simply minus one on the left and plus one on the right.',
    'Section 36.4': 'Before integrating a function in the modern sense, you must be able to measure the set of points where it exceeds any given level: where is the temperature above 30 degrees, and how much of the region is that? Functions for which every such question has an answer are called measurable. The requirement is weak: continuous functions qualify, and so do functions with jumps and limits of such functions, even discontinuous limits. On the interval from 0 to 1, the curves of x to the power 1, 2, 3 and so on settle down to a function that is 0 everywhere except for a jump to 1 at the very end, and that limit is still measurable.',
    'Section 38.5': 'Some constructions come in matched pairs, one building structure freely and the other forgetting it. Start with a plain set of letters and form every word you can spell with them: that is the free monoid on those letters. Going the other way, take any monoid and forget its multiplication, keeping only the underlying set. The two are linked by a perfect correspondence. Choosing where each letter should go inside a monoid is exactly the same as choosing a structure-respecting map from the free monoid into it, because once the letters are placed, every word’s image is forced. Pairs like this, one free and one forgetful, are adjoint functors, and they turn up in every corner of mathematics.',
    'Section 38.6': 'You can learn a great deal about a person from the company they keep, and category theory takes that idea to its limit. The Yoneda lemma says that an object is determined, up to isomorphism, by the maps going out of it to every other object, and it gives an exact count of the ways that pattern of maps can be matched with any other structure. Concretely, every natural way of turning maps out of an object into elements of some set is fixed by a single element of that set: the one to which the identity map is sent. It sounds abstract, but on a small example with three objects you can check it by counting.',
    'Section 38.7': 'A shopping list of shopping lists is still, in practice, one shopping list: you flatten it and get on with the shopping. And any single item can be treated as a list of one. Those two operations, wrapping a thing up and flattening nested layers, are the whole idea of a monad, provided they fit together sensibly: flattening three layers should give the same result whichever pair you flatten first, and wrapping then flattening should change nothing. Lists, optional values, probability distributions and computations with side effects all have this shape, which is why monads organise programming languages as well as algebra, where they appear as the shadow that every adjunction leaves behind.',
    'Section 39.3': 'Flip a coin that lands heads nine times out of ten, a hundred times over. Any sequence at all is possible, but in practice you will see something close to 90 heads, and every sequence with about 90 heads has almost exactly the same, very small, probability. These overwhelmingly likely outcomes form the typical set, and although it holds nearly all the probability, it contains only a tiny fraction of the possible sequences. That observation is the reason data compression works. You only need short labels for the typical sequences, and the number of bits per flip needed to label them is the entropy of the coin, about 0.47.',
    'Section 39.8': 'A telephone line, a Wi-Fi link or a deep-space radio carries a continuous signal blurred by random noise, and the question is how many bits each transmission can carry reliably. Claude Shannon answered it in 1948 with one of the most quoted formulas in engineering: the capacity depends only on the ratio of signal power to noise power. At a ratio of 3 the channel carries 1 bit per use; raising the ratio to 15, five times the power, buys only 2 bits. Capacity grows with the logarithm of the power, so each extra bit costs roughly a quadrupling of the ratio once it is large. This section builds the continuous version of entropy needed to prove it.',
    'Section 40.2': 'A musical score tells you which notes are played and when. The Fourier transform tells you only which frequencies are present, with no record of when they occur, so a melody and the same notes struck all at once look much alike. The natural fix is to analyse the signal through a short sliding window, but that runs into a hard limit. A short window pins down timing but blurs pitch; a long window resolves pitch but smears timing. Time and frequency cannot both be measured sharply, and the product of the two spreads can never fall below a fixed floor. A bell-shaped Gaussian pulse is the one shape that sits exactly on that floor.',
    'Section 40.3': 'A wavelet is a short wiggle that rises and falls back to nothing. Slide it along a signal and, at each position, measure how well the two match; then stretch the wavelet and do it again. Wide wavelets respond to slow trends, narrow ones to fine detail, and the result is a map showing which scales are active where. A sudden jump in the signal stands out, right at the moment it happens. Matching the simplest wavelet, a square up-and-down pulse two units wide, against a step from 0 to 1 gives a strong response, about 0.707 in size, exactly where the pulse straddles the jump, and nothing at all away from it.',
    'Section 40.4': 'Look at a photograph at low resolution, then add the detail needed for the next resolution, then the next. Each level contains everything in the coarser ones plus something extra, and in the limit you have the full picture. A multiresolution analysis is the mathematical form of that zooming. Its building block is a single bump. In the simplest case, the Haar system, the bump is a box of width 1, and that box is exactly two half-width boxes placed side by side. Coarse approximations are built from wide boxes, finer ones from narrower boxes, and the differences between successive levels are precisely what wavelets capture.',
    'Section 40.5': 'In a good coordinate system the axes are perpendicular and of unit length, so that each coordinate can be read off without reference to the others. An orthonormal wavelet basis gives signals that kind of coordinate system, built entirely from stretched and shifted copies of one wavelet, each stretch twice as narrow as the one before. The Haar wavelet, a box that steps up and then down, achieves this but is jagged. For decades it was unclear whether a smooth wavelet could also be confined to a finite interval and still give perpendicular coordinates. Ingrid Daubechies showed in 1988 that it can, at the price of a wider support for every gain in smoothness.',
    'Section 40.7': 'A wavelet coefficient measures how much a signal varies at a particular place and scale. If the signal is locally flat, a straight ramp or a gentle curve, a well-designed wavelet should report almost nothing there, saving its large coefficients for places where something happens, such as an edge. The number of polynomial degrees a wavelet ignores is its number of vanishing moments. The Haar wavelet ignores constants but not ramps: a ramp leaves small coefficients everywhere, while a genuine jump produces one six times larger than the rest. That is the key to compression, since smooth regions give tiny coefficients that can be discarded and only the edges need many bits.',
    'Section 42.5': 'An opinion poll that reports 52 per cent support, plus or minus 3, is doing two jobs: giving a best guess and admitting how wrong it might be. Estimation theory makes both jobs precise. A good estimate should aim at the right target on average, should not wobble too much from one sample to the next, and should improve as the sample grows. The confidence interval packages the uncertainty. A 95 per cent interval comes from a procedure that captures the true value in 95 of every 100 samples, which is a statement about the method rather than a promise about any one interval, a distinction that trips up even professional researchers.',
    'Section 43.2': 'Two fair coin tosses are independent: the chance of two heads is a half times a half, a quarter, because neither toss knows anything about the other. Probability needs that idea for whole families of events, and it hides a trap. Three events can be independent in every pair and still fail to be independent all together, as two coin tosses and the event that they agree demonstrate. The section also settles a question that sounds philosophical but is practical: does an infinite sequence of independent coin tosses actually exist as a mathematical object? Kolmogorov’s extension theorem says yes, and builds it from nothing more than the probabilities of finite stretches.',
    'Section 43.3': 'Your best guess of tomorrow’s temperature changes as information arrives: the forecast this morning, the clouds this afternoon, the wind tonight. Conditional expectation is the mathematics of that best guess. Given whatever information is currently available, it is the prediction that is right on average and that uses that information and nothing more. For a point chosen at random in a disc, learning its horizontal position narrows it down to a single vertical chord, and the best guess of its height is then the middle of that chord. When the information is a single event, the definition reduces to familiar conditional probability; this section extends it to information of any kind.',
    'Section 43.5': 'Toss a fair coin again and again and keep track of the fraction of heads. It wanders at first, but it settles down, and with probability one it settles on exactly one half. That is the strong law of large numbers, and this section proves it alongside a more general result about fair games. A fair game is one in which, given everything so far, your expected fortune tomorrow equals your fortune today. If such a game cannot drift off to infinity, it must eventually stop wobbling and converge. Pólya’s urn shows how: draw a ball, return it with another of the same colour, and the proportion of red settles down, though to a different value on every run.',
    'Section 43.6': 'Robert Brown, looking through a microscope in 1827, saw tiny particles from pollen grains jostling endlessly in water, kicked about by molecules far too small to see. The mathematical version of that motion is a path that moves continuously but changes direction at every instant, each stretch of it independent of the past, with its spread growing in proportion to elapsed time: after four seconds the typical distance from the start is twice what it was after one. It is the limit of a random walk with ever smaller and faster steps. The path is continuous everywhere yet differentiable nowhere, and it underlies models of diffusion, stock prices and electronic noise.',
    'Section 43.8': 'A board game played with dice has a useful kind of forgetfulness: where you go next depends only on the square you are on now, not on how you got there. Processes with this property are called Markov processes, and they model queues, chemical reactions, the spread of infections and the wandering of web surfers between pages. In continuous time the whole behaviour is summarised by the rates at which the process jumps from each state to each other. A machine that breaks down and is repaired at the same rate, switching each way at rate q, forgets which state it started in at rate 2q and settles into spending half its time in each.',
    'Section 45.6': 'Balancing a broom upright on your palm, you constantly trade two costs: letting the broom lean too far and moving your hand too much. Optimal control turns that trade-off into mathematics. You state, in a single number, how much you dislike errors and how much you dislike effort, and the theory delivers the control law that minimises the total over all time. For a linear system with quadratic costs, the linear-quadratic regulator, the answer is remarkably simple: feed back the current state, multiplied by a gain matrix found by solving one matrix equation. Applied to a system that would otherwise run away exponentially, it produces exponential decay back to rest.',
    'Section 46.2': 'A swinging pendulum is fully described at any instant by two numbers, its angle and its speed. Plot those two numbers as a point and, as time passes, the point traces a curve; draw the curves for every possible starting condition and you have a phase portrait, a single picture of everything the system can ever do. Closed loops mean repeating motion, points where curves converge mean rest, and curves that run off to infinity mean escape. For a mass on a spring, conservation of energy alone forces every curve to be a closed loop of fixed size, a circle in suitable units, with no equation solved. The rule that carries points along these curves is called a flow.',
    'Section 46.3': 'Zoom in far enough on a smooth curve and it looks like a straight line; zoom in on a smooth landscape and it looks like a tilted plane. The same idea applies to motion near a point of rest. Close to an equilibrium, a complicated nonlinear system behaves almost exactly like a much simpler linear one, and linear systems can be solved completely. If the linear version spirals inward, the real system does too; if it shows a saddle, with motion drawn in along one direction and flung out along another, so does the real system. The approximation can fail only in borderline cases, and this section identifies those cases precisely.',
    'Section 46.4': 'Many systems settle into a rhythm: a heartbeat, a dripping tap, the rise and fall of predators and prey. To decide whether such a rhythm is stable, Henri Poincaré had a clever idea. Instead of following the whole loop, place a checkpoint across it and record only where the system crosses it each time round. A continuous motion becomes a sequence of points, and the question becomes simple: do nearby crossings move closer to the loop’s own crossing, or further away? For the classic example in this section, a cycle at radius 1, trajectories starting inside and outside both spiral onto the cycle, and their crossings close in on it every time round.',
    'Section 46.5': 'A marble in a bowl comes to rest at the bottom, and you can be sure of that without solving any equation of motion: friction only ever drains its energy, and the energy is lowest at the bottom. Lyapunov’s method generalises that argument. Find any quantity that is smallest at the equilibrium and never increases as the system evolves, and you have proved the equilibrium stable without knowing a single trajectory. The quantity need not be physical energy; any function with those two properties will do, and finding one is something of an art. The method can also mark out a region of starting points guaranteed to settle, even when the full region is unknown.',
    'Section 46.6': 'A population that breeds in yearly generations can be modelled with a single rule: next year’s size is this year’s, multiplied by a growth factor and scaled down as the population nears the limit its environment can support. With a modest growth factor of 2.8, any starting population settles at about 64 per cent of that limit, overshooting and undershooting on the way. Raise the growth factor and the settled value splits into a two-year cycle, then four, then eight, and beyond about 3.57 the behaviour becomes chaotic: entirely deterministic, yet so sensitive to the starting value that long-term prediction is impossible. All of that comes from one line of arithmetic.',
    'Section 47.5': 'Every radio broadcast, every electric motor and every ray of light is governed by four equations, first gathered into a complete theory by James Clerk Maxwell in the 1860s. Two say what electric and magnetic fields can look like at any instant: electric field lines start and end on charges, while magnetic field lines never start or end at all. The other two say how the fields change: a changing magnetic field drives an electric one, which is how generators work, and a current or a changing electric field drives a magnetic one. Combine the two dynamical laws in empty space and they predict waves travelling at about 300,000 kilometres per second, the speed of light.',
    'Section 48.3': 'Training a machine-learning model means adjusting it to reduce its average error over millions of examples. Computing the exact downhill direction means looking at every example at every step, which is ruinously slow. Stochastic gradient descent looks at one example, or a small batch, finds the downhill direction for that, and takes a step. Each step is slightly wrong but right on average, and the errors largely cancel. On a simple bowl, starting at 10 and stepping a tenth of the slope each time, exact steps give 9, 8.1 and 7.29; this section’s noisy steps give 8.9, 8.11 and 7.199, wandering a little but tracking the same descent at a fraction of the cost.',
    'Section 49.3': 'Iterative solvers for large systems of equations converge quickly when a problem is well balanced and slowly when it is lopsided, with some directions far more sensitive than others. The ratio of the most to the least sensitive, the condition number, controls the speed. Preconditioning means first transforming the problem into an equivalent one with the same answer and a better balance. In this section’s example the two sensitivities differ by a factor of 50; simply rescaling each equation by its own diagonal entry brings that down to about 1.15, and the solver then finishes in a handful of steps. Multigrid, the other idea here, attacks the imbalance by working on coarse and fine grids together.',
    'Section 49.8': 'Simulate a planet orbiting the sun with the simplest step-by-step method and something odd happens: the planet slowly spirals outward, gaining energy from nowhere, because each step makes a small error that always pushes the same way. Over millions of orbits the simulation becomes nonsense, however small the step. Geometric integrators avoid this by respecting the structure of the physics rather than merely shrinking the error per step. A symplectic method still makes errors, but its energy wobbles around the true value instead of drifting away. In this section’s twelve-step example, the simple method’s energy climbs without limit while the symplectic method’s stays close to the truth.',
}

LITERAL = {}   # filled by literal_fixes.py if present

def literal_fixes(vol):
    try:
        import literal_fixes as L
        return L.FIXES.get(0, []) + L.FIXES.get(vol, [])
    except ImportError:
        return []
